/** Generated by scripts/generate-deployment-manifests.mjs before Convex deploy. */
export const DEPLOYMENT_MANIFEST = {
  schemaVersion: 1,
  service: "convex",
  mode: "development",
  gitSha: "0000000000000000000000000000000000000000",
  deploymentId: "local-convex-unbound",
  deployedAt: "1970-01-01T00:00:00.000Z",
} as const;
