allowBuilds:
  core-js: true
  esbuild: true
  sharp: true
  workerd: true

onlyBuiltDependencies:
  - "@tailwindcss/oxide"
  - core-js
  - esbuild
  - protobufjs
  - sharp
  - vue-demi
  - workerd
overrides:
  kysely: ~0.28.17
  vite: ^8.0.16
patchedDependencies:
  autumn-js@0.1.85: patches/autumn-js@0.1.85.patch
