"$schema" = "node_modules/wrangler/config-schema.json"
main = "@tanstack/react-start/server-entry"
name = "zevium-dev"
compatibility_date = "2025-09-02"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true
