/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AppRouteImport } from './routes/app'
import { Route as CatalogueRouteImport } from './routes/catalogue'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminOrgsRouteImport } from './routes/admin/orgs'
import { Route as AdminPayoutsRouteImport } from './routes/admin/payouts'
import { Route as AdminProjectsRouteImport } from './routes/admin/projects'
import { Route as AdminReviewsRouteImport } from './routes/admin/reviews'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppBillingRouteImport } from './routes/app/billing'
import { Route as AppEarningsRouteImport } from './routes/app/earnings'
import { Route as AppOrgRouteImport } from './routes/app/org'
import { Route as AppProjectsRouteImport } from './routes/app/projects'
import { Route as AppSettingsRouteImport } from './routes/app/settings'
import { Route as CatalogueIndexRouteImport } from './routes/catalogue/index'
import { Route as DocsIndexRouteImport } from './routes/docs/index'
import { Route as DocsAgentsRouteImport } from './routes/docs/agents'
import { Route as DocsConsumingRouteImport } from './routes/docs/consuming'
import { Route as DocsPublishingRouteImport } from './routes/docs/publishing'
import { Route as SignInSplatRouteImport } from './routes/sign-in.$'
import { Route as SignUpSplatRouteImport } from './routes/sign-up.$'
import { Route as AppOrgIndexRouteImport } from './routes/app/org/index'
import { Route as AppOrgCreateRouteImport } from './routes/app/org/create'
import { Route as AppProjectsIndexRouteImport } from './routes/app/projects/index'
import { Route as AppProjectsProjectSlugRouteImport } from './routes/app/projects/$projectSlug'
import { Route as AppProjectsCreateRouteImport } from './routes/app/projects/create'
import { Route as AppSettingsIndexRouteImport } from './routes/app/settings/index'
import { Route as AppSettingsActivityRouteImport } from './routes/app/settings/activity'
import { Route as AppSettingsKeysRouteImport } from './routes/app/settings/keys'
import { Route as CataloguePublisherHandleProjectSlugRouteImport } from './routes/catalogue/$publisherHandle.$projectSlug'
import { Route as AppProjectsProjectSlugSpecRouteImport } from './routes/app/projects/$projectSlug/spec'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogueRoute = CatalogueRouteImport.update({
  id: '/catalogue',
  path: '/catalogue',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrgsRoute = AdminOrgsRouteImport.update({
  id: '/orgs',
  path: '/orgs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPayoutsRoute = AdminPayoutsRouteImport.update({
  id: '/payouts',
  path: '/payouts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProjectsRoute = AdminProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReviewsRoute = AdminReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AdminRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppBillingRoute = AppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppRoute,
} as any)
const AppEarningsRoute = AppEarningsRouteImport.update({
  id: '/earnings',
  path: '/earnings',
  getParentRoute: () => AppRoute,
} as any)
const AppOrgRoute = AppOrgRouteImport.update({
  id: '/org',
  path: '/org',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsRoute = AppProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const CatalogueIndexRoute = CatalogueIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CatalogueRoute,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsAgentsRoute = DocsAgentsRouteImport.update({
  id: '/docs/agents',
  path: '/docs/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsConsumingRoute = DocsConsumingRouteImport.update({
  id: '/docs/consuming',
  path: '/docs/consuming',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsPublishingRoute = DocsPublishingRouteImport.update({
  id: '/docs/publishing',
  path: '/docs/publishing',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInSplatRoute = SignInSplatRouteImport.update({
  id: '/sign-in/$',
  path: '/sign-in/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpSplatRoute = SignUpSplatRouteImport.update({
  id: '/sign-up/$',
  path: '/sign-up/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppOrgIndexRoute = AppOrgIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppOrgRoute,
} as any)
const AppOrgCreateRoute = AppOrgCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AppOrgRoute,
} as any)
const AppProjectsIndexRoute = AppProjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppProjectsRoute,
} as any)
const AppProjectsProjectSlugRoute = AppProjectsProjectSlugRouteImport.update({
  id: '/$projectSlug',
  path: '/$projectSlug',
  getParentRoute: () => AppProjectsRoute,
} as any)
const AppProjectsCreateRoute = AppProjectsCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AppProjectsRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsActivityRoute = AppSettingsActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsKeysRoute = AppSettingsKeysRouteImport.update({
  id: '/keys',
  path: '/keys',
  getParentRoute: () => AppSettingsRoute,
} as any)
const CataloguePublisherHandleProjectSlugRoute =
  CataloguePublisherHandleProjectSlugRouteImport.update({
    id: '/$publisherHandle/$projectSlug',
    path: '/$publisherHandle/$projectSlug',
    getParentRoute: () => CatalogueRoute,
  } as any)
const AppProjectsProjectSlugSpecRoute =
  AppProjectsProjectSlugSpecRouteImport.update({
    id: '/spec',
    path: '/spec',
    getParentRoute: () => AppProjectsProjectSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/catalogue': typeof CatalogueRouteWithChildren
  '/admin/orgs': typeof AdminOrgsRoute
  '/admin/payouts': typeof AdminPayoutsRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/app/billing': typeof AppBillingRoute
  '/app/earnings': typeof AppEarningsRoute
  '/app/org': typeof AppOrgRouteWithChildren
  '/app/projects': typeof AppProjectsRouteWithChildren
  '/app/settings': typeof AppSettingsRouteWithChildren
  '/docs/agents': typeof DocsAgentsRoute
  '/docs/consuming': typeof DocsConsumingRoute
  '/docs/publishing': typeof DocsPublishingRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/catalogue/': typeof CatalogueIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/app/org/create': typeof AppOrgCreateRoute
  '/app/projects/$projectSlug': typeof AppProjectsProjectSlugRouteWithChildren
  '/app/projects/create': typeof AppProjectsCreateRoute
  '/app/settings/activity': typeof AppSettingsActivityRoute
  '/app/settings/keys': typeof AppSettingsKeysRoute
  '/catalogue/$publisherHandle/$projectSlug': typeof CataloguePublisherHandleProjectSlugRoute
  '/app/org/': typeof AppOrgIndexRoute
  '/app/projects/': typeof AppProjectsIndexRoute
  '/app/settings/': typeof AppSettingsIndexRoute
  '/app/projects/$projectSlug/spec': typeof AppProjectsProjectSlugSpecRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/orgs': typeof AdminOrgsRoute
  '/admin/payouts': typeof AdminPayoutsRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/app/billing': typeof AppBillingRoute
  '/app/earnings': typeof AppEarningsRoute
  '/docs/agents': typeof DocsAgentsRoute
  '/docs/consuming': typeof DocsConsumingRoute
  '/docs/publishing': typeof DocsPublishingRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
  '/catalogue': typeof CatalogueIndexRoute
  '/docs': typeof DocsIndexRoute
  '/app/org/create': typeof AppOrgCreateRoute
  '/app/projects/$projectSlug': typeof AppProjectsProjectSlugRouteWithChildren
  '/app/projects/create': typeof AppProjectsCreateRoute
  '/app/settings/activity': typeof AppSettingsActivityRoute
  '/app/settings/keys': typeof AppSettingsKeysRoute
  '/catalogue/$publisherHandle/$projectSlug': typeof CataloguePublisherHandleProjectSlugRoute
  '/app/org': typeof AppOrgIndexRoute
  '/app/projects': typeof AppProjectsIndexRoute
  '/app/settings': typeof AppSettingsIndexRoute
  '/app/projects/$projectSlug/spec': typeof AppProjectsProjectSlugSpecRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/catalogue': typeof CatalogueRouteWithChildren
  '/admin/orgs': typeof AdminOrgsRoute
  '/admin/payouts': typeof AdminPayoutsRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/app/billing': typeof AppBillingRoute
  '/app/earnings': typeof AppEarningsRoute
  '/app/org': typeof AppOrgRouteWithChildren
  '/app/projects': typeof AppProjectsRouteWithChildren
  '/app/settings': typeof AppSettingsRouteWithChildren
  '/docs/agents': typeof DocsAgentsRoute
  '/docs/consuming': typeof DocsConsumingRoute
  '/docs/publishing': typeof DocsPublishingRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/catalogue/': typeof CatalogueIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/app/org/create': typeof AppOrgCreateRoute
  '/app/projects/$projectSlug': typeof AppProjectsProjectSlugRouteWithChildren
  '/app/projects/create': typeof AppProjectsCreateRoute
  '/app/settings/activity': typeof AppSettingsActivityRoute
  '/app/settings/keys': typeof AppSettingsKeysRoute
  '/catalogue/$publisherHandle/$projectSlug': typeof CataloguePublisherHandleProjectSlugRoute
  '/app/org/': typeof AppOrgIndexRoute
  '/app/projects/': typeof AppProjectsIndexRoute
  '/app/settings/': typeof AppSettingsIndexRoute
  '/app/projects/$projectSlug/spec': typeof AppProjectsProjectSlugSpecRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/catalogue'
    | '/admin/orgs'
    | '/admin/payouts'
    | '/admin/projects'
    | '/admin/reviews'
    | '/app/billing'
    | '/app/earnings'
    | '/app/org'
    | '/app/projects'
    | '/app/settings'
    | '/docs/agents'
    | '/docs/consuming'
    | '/docs/publishing'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/admin/'
    | '/app/'
    | '/catalogue/'
    | '/docs/'
    | '/app/org/create'
    | '/app/projects/$projectSlug'
    | '/app/projects/create'
    | '/app/settings/activity'
    | '/app/settings/keys'
    | '/catalogue/$publisherHandle/$projectSlug'
    | '/app/org/'
    | '/app/projects/'
    | '/app/settings/'
    | '/app/projects/$projectSlug/spec'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/orgs'
    | '/admin/payouts'
    | '/admin/projects'
    | '/admin/reviews'
    | '/app/billing'
    | '/app/earnings'
    | '/docs/agents'
    | '/docs/consuming'
    | '/docs/publishing'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/admin'
    | '/app'
    | '/catalogue'
    | '/docs'
    | '/app/org/create'
    | '/app/projects/$projectSlug'
    | '/app/projects/create'
    | '/app/settings/activity'
    | '/app/settings/keys'
    | '/catalogue/$publisherHandle/$projectSlug'
    | '/app/org'
    | '/app/projects'
    | '/app/settings'
    | '/app/projects/$projectSlug/spec'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/catalogue'
    | '/admin/orgs'
    | '/admin/payouts'
    | '/admin/projects'
    | '/admin/reviews'
    | '/app/billing'
    | '/app/earnings'
    | '/app/org'
    | '/app/projects'
    | '/app/settings'
    | '/docs/agents'
    | '/docs/consuming'
    | '/docs/publishing'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/admin/'
    | '/app/'
    | '/catalogue/'
    | '/docs/'
    | '/app/org/create'
    | '/app/projects/$projectSlug'
    | '/app/projects/create'
    | '/app/settings/activity'
    | '/app/settings/keys'
    | '/catalogue/$publisherHandle/$projectSlug'
    | '/app/org/'
    | '/app/projects/'
    | '/app/settings/'
    | '/app/projects/$projectSlug/spec'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  CatalogueRoute: typeof CatalogueRouteWithChildren
  DocsAgentsRoute: typeof DocsAgentsRoute
  DocsConsumingRoute: typeof DocsConsumingRoute
  DocsPublishingRoute: typeof DocsPublishingRoute
  SignInSplatRoute: typeof SignInSplatRoute
  SignUpSplatRoute: typeof SignUpSplatRoute
  DocsIndexRoute: typeof DocsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogue': {
      id: '/catalogue'
      path: '/catalogue'
      fullPath: '/catalogue'
      preLoaderRoute: typeof CatalogueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orgs': {
      id: '/admin/orgs'
      path: '/orgs'
      fullPath: '/admin/orgs'
      preLoaderRoute: typeof AdminOrgsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payouts': {
      id: '/admin/payouts'
      path: '/payouts'
      fullPath: '/admin/payouts'
      preLoaderRoute: typeof AdminPayoutsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/projects': {
      id: '/admin/projects'
      path: '/projects'
      fullPath: '/admin/projects'
      preLoaderRoute: typeof AdminProjectsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reviews': {
      id: '/admin/reviews'
      path: '/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AdminReviewsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/billing': {
      id: '/app/billing'
      path: '/billing'
      fullPath: '/app/billing'
      preLoaderRoute: typeof AppBillingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/earnings': {
      id: '/app/earnings'
      path: '/earnings'
      fullPath: '/app/earnings'
      preLoaderRoute: typeof AppEarningsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/org': {
      id: '/app/org'
      path: '/org'
      fullPath: '/app/org'
      preLoaderRoute: typeof AppOrgRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/projects': {
      id: '/app/projects'
      path: '/projects'
      fullPath: '/app/projects'
      preLoaderRoute: typeof AppProjectsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/catalogue/': {
      id: '/catalogue/'
      path: '/'
      fullPath: '/catalogue/'
      preLoaderRoute: typeof CatalogueIndexRouteImport
      parentRoute: typeof CatalogueRoute
    }
    '/docs/': {
      id: '/docs/'
      path: '/docs'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/agents': {
      id: '/docs/agents'
      path: '/docs/agents'
      fullPath: '/docs/agents'
      preLoaderRoute: typeof DocsAgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/consuming': {
      id: '/docs/consuming'
      path: '/docs/consuming'
      fullPath: '/docs/consuming'
      preLoaderRoute: typeof DocsConsumingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/publishing': {
      id: '/docs/publishing'
      path: '/docs/publishing'
      fullPath: '/docs/publishing'
      preLoaderRoute: typeof DocsPublishingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in/$': {
      id: '/sign-in/$'
      path: '/sign-in/$'
      fullPath: '/sign-in/$'
      preLoaderRoute: typeof SignInSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up/$': {
      id: '/sign-up/$'
      path: '/sign-up/$'
      fullPath: '/sign-up/$'
      preLoaderRoute: typeof SignUpSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/org/': {
      id: '/app/org/'
      path: '/'
      fullPath: '/app/org/'
      preLoaderRoute: typeof AppOrgIndexRouteImport
      parentRoute: typeof AppOrgRoute
    }
    '/app/org/create': {
      id: '/app/org/create'
      path: '/create'
      fullPath: '/app/org/create'
      preLoaderRoute: typeof AppOrgCreateRouteImport
      parentRoute: typeof AppOrgRoute
    }
    '/app/projects/': {
      id: '/app/projects/'
      path: '/'
      fullPath: '/app/projects/'
      preLoaderRoute: typeof AppProjectsIndexRouteImport
      parentRoute: typeof AppProjectsRoute
    }
    '/app/projects/$projectSlug': {
      id: '/app/projects/$projectSlug'
      path: '/$projectSlug'
      fullPath: '/app/projects/$projectSlug'
      preLoaderRoute: typeof AppProjectsProjectSlugRouteImport
      parentRoute: typeof AppProjectsRoute
    }
    '/app/projects/create': {
      id: '/app/projects/create'
      path: '/create'
      fullPath: '/app/projects/create'
      preLoaderRoute: typeof AppProjectsCreateRouteImport
      parentRoute: typeof AppProjectsRoute
    }
    '/app/settings/': {
      id: '/app/settings/'
      path: '/'
      fullPath: '/app/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/app/settings/activity': {
      id: '/app/settings/activity'
      path: '/activity'
      fullPath: '/app/settings/activity'
      preLoaderRoute: typeof AppSettingsActivityRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/app/settings/keys': {
      id: '/app/settings/keys'
      path: '/keys'
      fullPath: '/app/settings/keys'
      preLoaderRoute: typeof AppSettingsKeysRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/catalogue/$publisherHandle/$projectSlug': {
      id: '/catalogue/$publisherHandle/$projectSlug'
      path: '/$publisherHandle/$projectSlug'
      fullPath: '/catalogue/$publisherHandle/$projectSlug'
      preLoaderRoute: typeof CataloguePublisherHandleProjectSlugRouteImport
      parentRoute: typeof CatalogueRoute
    }
    '/app/projects/$projectSlug/spec': {
      id: '/app/projects/$projectSlug/spec'
      path: '/spec'
      fullPath: '/app/projects/$projectSlug/spec'
      preLoaderRoute: typeof AppProjectsProjectSlugSpecRouteImport
      parentRoute: typeof AppProjectsProjectSlugRoute
    }
  }
}

interface AdminRouteChildren {
  AdminOrgsRoute: typeof AdminOrgsRoute
  AdminPayoutsRoute: typeof AdminPayoutsRoute
  AdminProjectsRoute: typeof AdminProjectsRoute
  AdminReviewsRoute: typeof AdminReviewsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminOrgsRoute: AdminOrgsRoute,
  AdminPayoutsRoute: AdminPayoutsRoute,
  AdminProjectsRoute: AdminProjectsRoute,
  AdminReviewsRoute: AdminReviewsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppOrgRouteChildren {
  AppOrgCreateRoute: typeof AppOrgCreateRoute
  AppOrgIndexRoute: typeof AppOrgIndexRoute
}

const AppOrgRouteChildren: AppOrgRouteChildren = {
  AppOrgCreateRoute: AppOrgCreateRoute,
  AppOrgIndexRoute: AppOrgIndexRoute,
}

const AppOrgRouteWithChildren =
  AppOrgRoute._addFileChildren(AppOrgRouteChildren)

interface AppProjectsProjectSlugRouteChildren {
  AppProjectsProjectSlugSpecRoute: typeof AppProjectsProjectSlugSpecRoute
}

const AppProjectsProjectSlugRouteChildren: AppProjectsProjectSlugRouteChildren =
  {
    AppProjectsProjectSlugSpecRoute: AppProjectsProjectSlugSpecRoute,
  }

const AppProjectsProjectSlugRouteWithChildren =
  AppProjectsProjectSlugRoute._addFileChildren(
    AppProjectsProjectSlugRouteChildren,
  )

interface AppProjectsRouteChildren {
  AppProjectsProjectSlugRoute: typeof AppProjectsProjectSlugRouteWithChildren
  AppProjectsCreateRoute: typeof AppProjectsCreateRoute
  AppProjectsIndexRoute: typeof AppProjectsIndexRoute
}

const AppProjectsRouteChildren: AppProjectsRouteChildren = {
  AppProjectsProjectSlugRoute: AppProjectsProjectSlugRouteWithChildren,
  AppProjectsCreateRoute: AppProjectsCreateRoute,
  AppProjectsIndexRoute: AppProjectsIndexRoute,
}

const AppProjectsRouteWithChildren = AppProjectsRoute._addFileChildren(
  AppProjectsRouteChildren,
)

interface AppSettingsRouteChildren {
  AppSettingsActivityRoute: typeof AppSettingsActivityRoute
  AppSettingsKeysRoute: typeof AppSettingsKeysRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
}

const AppSettingsRouteChildren: AppSettingsRouteChildren = {
  AppSettingsActivityRoute: AppSettingsActivityRoute,
  AppSettingsKeysRoute: AppSettingsKeysRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
}

const AppSettingsRouteWithChildren = AppSettingsRoute._addFileChildren(
  AppSettingsRouteChildren,
)

interface AppRouteChildren {
  AppBillingRoute: typeof AppBillingRoute
  AppEarningsRoute: typeof AppEarningsRoute
  AppOrgRoute: typeof AppOrgRouteWithChildren
  AppProjectsRoute: typeof AppProjectsRouteWithChildren
  AppSettingsRoute: typeof AppSettingsRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBillingRoute: AppBillingRoute,
  AppEarningsRoute: AppEarningsRoute,
  AppOrgRoute: AppOrgRouteWithChildren,
  AppProjectsRoute: AppProjectsRouteWithChildren,
  AppSettingsRoute: AppSettingsRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface CatalogueRouteChildren {
  CatalogueIndexRoute: typeof CatalogueIndexRoute
  CataloguePublisherHandleProjectSlugRoute: typeof CataloguePublisherHandleProjectSlugRoute
}

const CatalogueRouteChildren: CatalogueRouteChildren = {
  CatalogueIndexRoute: CatalogueIndexRoute,
  CataloguePublisherHandleProjectSlugRoute:
    CataloguePublisherHandleProjectSlugRoute,
}

const CatalogueRouteWithChildren = CatalogueRoute._addFileChildren(
  CatalogueRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  CatalogueRoute: CatalogueRouteWithChildren,
  DocsAgentsRoute: DocsAgentsRoute,
  DocsConsumingRoute: DocsConsumingRoute,
  DocsPublishingRoute: DocsPublishingRoute,
  SignInSplatRoute: SignInSplatRoute,
  SignUpSplatRoute: SignUpSplatRoute,
  DocsIndexRoute: DocsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
