/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CatalogueRouteImport } from './routes/catalogue'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as SignUpSplatRouteImport } from './routes/sign-up.$'
import { Route as SignInSplatRouteImport } from './routes/sign-in.$'
import { Route as AppSettingsRouteImport } from './routes/app/settings'
import { Route as AppProjectsRouteImport } from './routes/app/projects'
import { Route as AppBillingRouteImport } from './routes/app/billing'
import { Route as AppSettingsIndexRouteImport } from './routes/app/settings/index'
import { Route as AppProjectsIndexRouteImport } from './routes/app/projects/index'
import { Route as AppSettingsKeysRouteImport } from './routes/app/settings/keys'
import { Route as AppSettingsActivityRouteImport } from './routes/app/settings/activity'
import { Route as AppProjectsCreateRouteImport } from './routes/app/projects/create'
import { Route as AppProjectsProjectSlugRouteImport } from './routes/app/projects/$projectSlug'
import { Route as AppProjectsProjectSlugSpecRouteImport } from './routes/app/projects/$projectSlug/spec'

const CatalogueRoute = CatalogueRouteImport.update({
  id: '/catalogue',
  path: '/catalogue',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const SignUpSplatRoute = SignUpSplatRouteImport.update({
  id: '/sign-up/$',
  path: '/sign-up/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInSplatRoute = SignInSplatRouteImport.update({
  id: '/sign-in/$',
  path: '/sign-in/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsRoute = AppProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AppRoute,
} as any)
const AppBillingRoute = AppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppProjectsIndexRoute = AppProjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppProjectsRoute,
} as any)
const AppSettingsKeysRoute = AppSettingsKeysRouteImport.update({
  id: '/keys',
  path: '/keys',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsActivityRoute = AppSettingsActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppProjectsCreateRoute = AppProjectsCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AppProjectsRoute,
} as any)
const AppProjectsProjectSlugRoute = AppProjectsProjectSlugRouteImport.update({
  id: '/$projectSlug',
  path: '/$projectSlug',
  getParentRoute: () => AppProjectsRoute,
} as any)
const AppProjectsProjectSlugSpecRoute =
  AppProjectsProjectSlugSpecRouteImport.update({
    id: '/spec',
    path: '/spec',
    getParentRoute: () => AppProjectsProjectSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/catalogue': typeof CatalogueRoute
  '/app/billing': typeof AppBillingRoute
  '/app/projects': typeof AppProjectsRouteWithChildren
  '/app/settings': typeof AppSettingsRouteWithChildren
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/app/': typeof AppIndexRoute
  '/app/projects/$projectSlug': typeof AppProjectsProjectSlugRouteWithChildren
  '/app/projects/create': typeof AppProjectsCreateRoute
  '/app/settings/activity': typeof AppSettingsActivityRoute
  '/app/settings/keys': typeof AppSettingsKeysRoute
  '/app/projects/': typeof AppProjectsIndexRoute
  '/app/settings/': typeof AppSettingsIndexRoute
  '/app/projects/$projectSlug/spec': typeof AppProjectsProjectSlugSpecRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/catalogue': typeof CatalogueRoute
  '/app/billing': typeof AppBillingRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/app': typeof AppIndexRoute
  '/app/projects/$projectSlug': typeof AppProjectsProjectSlugRouteWithChildren
  '/app/projects/create': typeof AppProjectsCreateRoute
  '/app/settings/activity': typeof AppSettingsActivityRoute
  '/app/settings/keys': typeof AppSettingsKeysRoute
  '/app/projects': typeof AppProjectsIndexRoute
  '/app/settings': typeof AppSettingsIndexRoute
  '/app/projects/$projectSlug/spec': typeof AppProjectsProjectSlugSpecRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/catalogue': typeof CatalogueRoute
  '/app/billing': typeof AppBillingRoute
  '/app/projects': typeof AppProjectsRouteWithChildren
  '/app/settings': typeof AppSettingsRouteWithChildren
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/app/': typeof AppIndexRoute
  '/app/projects/$projectSlug': typeof AppProjectsProjectSlugRouteWithChildren
  '/app/projects/create': typeof AppProjectsCreateRoute
  '/app/settings/activity': typeof AppSettingsActivityRoute
  '/app/settings/keys': typeof AppSettingsKeysRoute
  '/app/projects/': typeof AppProjectsIndexRoute
  '/app/settings/': typeof AppSettingsIndexRoute
  '/app/projects/$projectSlug/spec': typeof AppProjectsProjectSlugSpecRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/catalogue'
    | '/app/billing'
    | '/app/projects'
    | '/app/settings'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/app/'
    | '/app/projects/$projectSlug'
    | '/app/projects/create'
    | '/app/settings/activity'
    | '/app/settings/keys'
    | '/app/projects/'
    | '/app/settings/'
    | '/app/projects/$projectSlug/spec'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/catalogue'
    | '/app/billing'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/app'
    | '/app/projects/$projectSlug'
    | '/app/projects/create'
    | '/app/settings/activity'
    | '/app/settings/keys'
    | '/app/projects'
    | '/app/settings'
    | '/app/projects/$projectSlug/spec'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/catalogue'
    | '/app/billing'
    | '/app/projects'
    | '/app/settings'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/app/'
    | '/app/projects/$projectSlug'
    | '/app/projects/create'
    | '/app/settings/activity'
    | '/app/settings/keys'
    | '/app/projects/'
    | '/app/settings/'
    | '/app/projects/$projectSlug/spec'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  CatalogueRoute: typeof CatalogueRoute
  SignInSplatRoute: typeof SignInSplatRoute
  SignUpSplatRoute: typeof SignUpSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/catalogue': {
      id: '/catalogue'
      path: '/catalogue'
      fullPath: '/catalogue'
      preLoaderRoute: typeof CatalogueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/sign-up/$': {
      id: '/sign-up/$'
      path: '/sign-up/$'
      fullPath: '/sign-up/$'
      preLoaderRoute: typeof SignUpSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in/$': {
      id: '/sign-in/$'
      path: '/sign-in/$'
      fullPath: '/sign-in/$'
      preLoaderRoute: typeof SignInSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/projects': {
      id: '/app/projects'
      path: '/projects'
      fullPath: '/app/projects'
      preLoaderRoute: typeof AppProjectsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/billing': {
      id: '/app/billing'
      path: '/billing'
      fullPath: '/app/billing'
      preLoaderRoute: typeof AppBillingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings/': {
      id: '/app/settings/'
      path: '/'
      fullPath: '/app/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/app/projects/': {
      id: '/app/projects/'
      path: '/'
      fullPath: '/app/projects/'
      preLoaderRoute: typeof AppProjectsIndexRouteImport
      parentRoute: typeof AppProjectsRoute
    }
    '/app/settings/keys': {
      id: '/app/settings/keys'
      path: '/keys'
      fullPath: '/app/settings/keys'
      preLoaderRoute: typeof AppSettingsKeysRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/app/settings/activity': {
      id: '/app/settings/activity'
      path: '/activity'
      fullPath: '/app/settings/activity'
      preLoaderRoute: typeof AppSettingsActivityRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/app/projects/create': {
      id: '/app/projects/create'
      path: '/create'
      fullPath: '/app/projects/create'
      preLoaderRoute: typeof AppProjectsCreateRouteImport
      parentRoute: typeof AppProjectsRoute
    }
    '/app/projects/$projectSlug': {
      id: '/app/projects/$projectSlug'
      path: '/$projectSlug'
      fullPath: '/app/projects/$projectSlug'
      preLoaderRoute: typeof AppProjectsProjectSlugRouteImport
      parentRoute: typeof AppProjectsRoute
    }
    '/app/projects/$projectSlug/spec': {
      id: '/app/projects/$projectSlug/spec'
      path: '/spec'
      fullPath: '/app/projects/$projectSlug/spec'
      preLoaderRoute: typeof AppProjectsProjectSlugSpecRouteImport
      parentRoute: typeof AppProjectsProjectSlugRoute
    }
  }
}

interface AppProjectsProjectSlugRouteChildren {
  AppProjectsProjectSlugSpecRoute: typeof AppProjectsProjectSlugSpecRoute
}

const AppProjectsProjectSlugRouteChildren: AppProjectsProjectSlugRouteChildren =
  {
    AppProjectsProjectSlugSpecRoute: AppProjectsProjectSlugSpecRoute,
  }

const AppProjectsProjectSlugRouteWithChildren =
  AppProjectsProjectSlugRoute._addFileChildren(
    AppProjectsProjectSlugRouteChildren,
  )

interface AppProjectsRouteChildren {
  AppProjectsProjectSlugRoute: typeof AppProjectsProjectSlugRouteWithChildren
  AppProjectsCreateRoute: typeof AppProjectsCreateRoute
  AppProjectsIndexRoute: typeof AppProjectsIndexRoute
}

const AppProjectsRouteChildren: AppProjectsRouteChildren = {
  AppProjectsProjectSlugRoute: AppProjectsProjectSlugRouteWithChildren,
  AppProjectsCreateRoute: AppProjectsCreateRoute,
  AppProjectsIndexRoute: AppProjectsIndexRoute,
}

const AppProjectsRouteWithChildren = AppProjectsRoute._addFileChildren(
  AppProjectsRouteChildren,
)

interface AppSettingsRouteChildren {
  AppSettingsActivityRoute: typeof AppSettingsActivityRoute
  AppSettingsKeysRoute: typeof AppSettingsKeysRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
}

const AppSettingsRouteChildren: AppSettingsRouteChildren = {
  AppSettingsActivityRoute: AppSettingsActivityRoute,
  AppSettingsKeysRoute: AppSettingsKeysRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
}

const AppSettingsRouteWithChildren = AppSettingsRoute._addFileChildren(
  AppSettingsRouteChildren,
)

interface AppRouteChildren {
  AppBillingRoute: typeof AppBillingRoute
  AppProjectsRoute: typeof AppProjectsRouteWithChildren
  AppSettingsRoute: typeof AppSettingsRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBillingRoute: AppBillingRoute,
  AppProjectsRoute: AppProjectsRouteWithChildren,
  AppSettingsRoute: AppSettingsRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  CatalogueRoute: CatalogueRoute,
  SignInSplatRoute: SignInSplatRoute,
  SignUpSplatRoute: SignUpSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
