import { type } from "arktype";

const ServerEnvArk = type({
  AUTH_GOOGLE_CLIENT_ID: "string",
  AUTH_GOOGLE_CLIENT_SECRET: "string",
  CAP_SECRET: "string",
  COHERE_API_KEY: "string | undefined",
  GEMINI_API_KEY: "string",
  LIBSQL_SECRET: "string",
  LIBSQL_URL: "string",
  POLAR_ACCESS_TOKEN: "string",
  POLAR_METER_ID: "string",
  POLAR_SERVER: "'sandbox' | 'production'",
  POLAR_WEBHOOK_SECRET: "string",
  PROXY_ALLOWED_HOSTS: "string > 0",
  PROXY_HOST_UNIT_COSTS: type("string.json.parse").pipe(type({ "[string]": "0 < number <= 1000000" }).and(type({}))),
  PROXY_PUBLIC_HOST: "string",
  PROXY_REQUEST_TIMEOUT_MS: "0 < number <= 300000",
  PROXY_UPSTREAM_SECRET: "string > 0",
  RESEND_API_KEY: "string",
  SECRETS_KEYS_JSON: type("string.json.parse").pipe(type({ id: "string > 0", key: "string > 0" }, "[]")),
  SECRETS_PRIMARY_KEY_ID: "string",
  UPSTASH_REDIS_REST_TOKEN: "string",
  UPSTASH_REDIS_REST_URL: "string.url",
  VITE_PUBLIC_POSTHOG_KEY: "string | undefined",
});

export type ServerEnv = typeof ServerEnvArk.infer;

export const serverEnv = ServerEnvArk.assert({
  AUTH_GOOGLE_CLIENT_ID: process.env.AUTH_GOOGLE_CLIENT_ID,
  AUTH_GOOGLE_CLIENT_SECRET: process.env.AUTH_GOOGLE_CLIENT_SECRET,
  CAP_SECRET: process.env.CAP_SECRET,
  COHERE_API_KEY: process.env.COHERE_API_KEY,
  GEMINI_API_KEY: process.env.GEMINI_API_KEY,
  LIBSQL_SECRET: process.env.LIBSQL_SECRET,
  LIBSQL_URL: process.env.LIBSQL_URL,
  POLAR_ACCESS_TOKEN: process.env.POLAR_ACCESS_TOKEN,
  POLAR_METER_ID: process.env.POLAR_METER_ID,
  POLAR_SERVER: process.env.POLAR_SERVER ?? "sandbox",
  POLAR_WEBHOOK_SECRET: process.env.POLAR_WEBHOOK_SECRET,
  PROXY_ALLOWED_HOSTS: process.env.PROXY_ALLOWED_HOSTS,
  PROXY_HOST_UNIT_COSTS: process.env.PROXY_HOST_UNIT_COSTS,
  PROXY_PUBLIC_HOST: process.env.PROXY_PUBLIC_HOST,
  PROXY_REQUEST_TIMEOUT_MS: Number(process.env.PROXY_REQUEST_TIMEOUT_MS ?? 0),
  PROXY_UPSTREAM_SECRET: process.env.PROXY_UPSTREAM_SECRET,
  RESEND_API_KEY: process.env.RESEND_API_KEY,
  SECRETS_KEYS_JSON: process.env.SECRETS_KEYS_JSON,
  SECRETS_PRIMARY_KEY_ID: process.env.SECRETS_PRIMARY_KEY_ID,
  UPSTASH_REDIS_REST_TOKEN: process.env.UPSTASH_REDIS_REST_TOKEN,
  UPSTASH_REDIS_REST_URL: process.env.UPSTASH_REDIS_REST_URL,
  VITE_PUBLIC_POSTHOG_KEY: process.env.VITE_PUBLIC_POSTHOG_KEY,
});
