/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'
import { createServerRootRoute } from '@tanstack/react-start/server'

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsSplatRouteImport } from './routes/settings/$'
import { ServerRoute as ApiTrpcSplatServerRouteImport } from './routes/api/trpc/$'
import { ServerRoute as ApiPosthogSplatServerRouteImport } from './routes/api/posthog/$'
import { ServerRoute as ApiOpenapiSplatServerRouteImport } from './routes/api/openapi/$'
import { ServerRoute as ApiAuthSplatServerRouteImport } from './routes/api/auth/$'

const CatalogueLazyRouteImport = createFileRoute('/catalogue')()
const IndexLazyRouteImport = createFileRoute('/')()
const ProjectsIndexLazyRouteImport = createFileRoute('/projects/')()
const OrganizationsIndexLazyRouteImport = createFileRoute('/organizations/')()
const ProjectsSlugLazyRouteImport = createFileRoute('/projects/$slug')()
const OrganizationsSlugLazyRouteImport = createFileRoute(
  '/organizations/$slug',
)()
const SettingsPreferenceSplatLazyRouteImport = createFileRoute(
  '/settings/preference/$',
)()
const SettingsKeysSplatLazyRouteImport = createFileRoute('/settings/keys/$')()
const SettingsCreditsSplatLazyRouteImport = createFileRoute(
  '/settings/credits/$',
)()
const SettingsActivitySplatLazyRouteImport = createFileRoute(
  '/settings/activity/$',
)()
const ProjectsSlugViewVersionLazyRouteImport = createFileRoute(
  '/projects/$slug/view/$version',
)()
const rootServerRouteImport = createServerRootRoute()

const CatalogueLazyRoute = CatalogueLazyRouteImport.update({
  id: '/catalogue',
  path: '/catalogue',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/catalogue.lazy').then((d) => d.Route))
const IndexLazyRoute = IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const ProjectsIndexLazyRoute = ProjectsIndexLazyRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/projects/index.lazy').then((d) => d.Route),
)
const OrganizationsIndexLazyRoute = OrganizationsIndexLazyRouteImport.update({
  id: '/organizations/',
  path: '/organizations/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/organizations/index.lazy').then((d) => d.Route),
)
const ProjectsSlugLazyRoute = ProjectsSlugLazyRouteImport.update({
  id: '/projects/$slug',
  path: '/projects/$slug',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/projects/$slug.lazy').then((d) => d.Route),
)
const OrganizationsSlugLazyRoute = OrganizationsSlugLazyRouteImport.update({
  id: '/organizations/$slug',
  path: '/organizations/$slug',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/organizations/$slug.lazy').then((d) => d.Route),
)
const SettingsSplatRoute = SettingsSplatRouteImport.update({
  id: '/settings/$',
  path: '/settings/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsPreferenceSplatLazyRoute =
  SettingsPreferenceSplatLazyRouteImport.update({
    id: '/settings/preference/$',
    path: '/settings/preference/$',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/settings/preference/$.lazy').then((d) => d.Route),
  )
const SettingsKeysSplatLazyRoute = SettingsKeysSplatLazyRouteImport.update({
  id: '/settings/keys/$',
  path: '/settings/keys/$',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/settings/keys/$.lazy').then((d) => d.Route),
)
const SettingsCreditsSplatLazyRoute =
  SettingsCreditsSplatLazyRouteImport.update({
    id: '/settings/credits/$',
    path: '/settings/credits/$',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/settings/credits/$.lazy').then((d) => d.Route),
  )
const SettingsActivitySplatLazyRoute =
  SettingsActivitySplatLazyRouteImport.update({
    id: '/settings/activity/$',
    path: '/settings/activity/$',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/settings/activity/$.lazy').then((d) => d.Route),
  )
const ProjectsSlugViewVersionLazyRoute =
  ProjectsSlugViewVersionLazyRouteImport.update({
    id: '/view/$version',
    path: '/view/$version',
    getParentRoute: () => ProjectsSlugLazyRoute,
  } as any).lazy(() =>
    import('./routes/projects/$slug/view/$version.lazy').then((d) => d.Route),
  )
const ApiTrpcSplatServerRoute = ApiTrpcSplatServerRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiPosthogSplatServerRoute = ApiPosthogSplatServerRouteImport.update({
  id: '/api/posthog/$',
  path: '/api/posthog/$',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiOpenapiSplatServerRoute = ApiOpenapiSplatServerRouteImport.update({
  id: '/api/openapi/$',
  path: '/api/openapi/$',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiAuthSplatServerRoute = ApiAuthSplatServerRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootServerRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/catalogue': typeof CatalogueLazyRoute
  '/settings/$': typeof SettingsSplatRoute
  '/organizations/$slug': typeof OrganizationsSlugLazyRoute
  '/projects/$slug': typeof ProjectsSlugLazyRouteWithChildren
  '/organizations': typeof OrganizationsIndexLazyRoute
  '/projects': typeof ProjectsIndexLazyRoute
  '/settings/activity/$': typeof SettingsActivitySplatLazyRoute
  '/settings/credits/$': typeof SettingsCreditsSplatLazyRoute
  '/settings/keys/$': typeof SettingsKeysSplatLazyRoute
  '/settings/preference/$': typeof SettingsPreferenceSplatLazyRoute
  '/projects/$slug/view/$version': typeof ProjectsSlugViewVersionLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/catalogue': typeof CatalogueLazyRoute
  '/settings/$': typeof SettingsSplatRoute
  '/organizations/$slug': typeof OrganizationsSlugLazyRoute
  '/projects/$slug': typeof ProjectsSlugLazyRouteWithChildren
  '/organizations': typeof OrganizationsIndexLazyRoute
  '/projects': typeof ProjectsIndexLazyRoute
  '/settings/activity/$': typeof SettingsActivitySplatLazyRoute
  '/settings/credits/$': typeof SettingsCreditsSplatLazyRoute
  '/settings/keys/$': typeof SettingsKeysSplatLazyRoute
  '/settings/preference/$': typeof SettingsPreferenceSplatLazyRoute
  '/projects/$slug/view/$version': typeof ProjectsSlugViewVersionLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexLazyRoute
  '/catalogue': typeof CatalogueLazyRoute
  '/settings/$': typeof SettingsSplatRoute
  '/organizations/$slug': typeof OrganizationsSlugLazyRoute
  '/projects/$slug': typeof ProjectsSlugLazyRouteWithChildren
  '/organizations/': typeof OrganizationsIndexLazyRoute
  '/projects/': typeof ProjectsIndexLazyRoute
  '/settings/activity/$': typeof SettingsActivitySplatLazyRoute
  '/settings/credits/$': typeof SettingsCreditsSplatLazyRoute
  '/settings/keys/$': typeof SettingsKeysSplatLazyRoute
  '/settings/preference/$': typeof SettingsPreferenceSplatLazyRoute
  '/projects/$slug/view/$version': typeof ProjectsSlugViewVersionLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/catalogue'
    | '/settings/$'
    | '/organizations/$slug'
    | '/projects/$slug'
    | '/organizations'
    | '/projects'
    | '/settings/activity/$'
    | '/settings/credits/$'
    | '/settings/keys/$'
    | '/settings/preference/$'
    | '/projects/$slug/view/$version'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/catalogue'
    | '/settings/$'
    | '/organizations/$slug'
    | '/projects/$slug'
    | '/organizations'
    | '/projects'
    | '/settings/activity/$'
    | '/settings/credits/$'
    | '/settings/keys/$'
    | '/settings/preference/$'
    | '/projects/$slug/view/$version'
  id:
    | '__root__'
    | '/'
    | '/catalogue'
    | '/settings/$'
    | '/organizations/$slug'
    | '/projects/$slug'
    | '/organizations/'
    | '/projects/'
    | '/settings/activity/$'
    | '/settings/credits/$'
    | '/settings/keys/$'
    | '/settings/preference/$'
    | '/projects/$slug/view/$version'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  CatalogueLazyRoute: typeof CatalogueLazyRoute
  SettingsSplatRoute: typeof SettingsSplatRoute
  OrganizationsSlugLazyRoute: typeof OrganizationsSlugLazyRoute
  ProjectsSlugLazyRoute: typeof ProjectsSlugLazyRouteWithChildren
  OrganizationsIndexLazyRoute: typeof OrganizationsIndexLazyRoute
  ProjectsIndexLazyRoute: typeof ProjectsIndexLazyRoute
  SettingsActivitySplatLazyRoute: typeof SettingsActivitySplatLazyRoute
  SettingsCreditsSplatLazyRoute: typeof SettingsCreditsSplatLazyRoute
  SettingsKeysSplatLazyRoute: typeof SettingsKeysSplatLazyRoute
  SettingsPreferenceSplatLazyRoute: typeof SettingsPreferenceSplatLazyRoute
}
export interface FileServerRoutesByFullPath {
  '/api/auth/$': typeof ApiAuthSplatServerRoute
  '/api/openapi/$': typeof ApiOpenapiSplatServerRoute
  '/api/posthog/$': typeof ApiPosthogSplatServerRoute
  '/api/trpc/$': typeof ApiTrpcSplatServerRoute
}
export interface FileServerRoutesByTo {
  '/api/auth/$': typeof ApiAuthSplatServerRoute
  '/api/openapi/$': typeof ApiOpenapiSplatServerRoute
  '/api/posthog/$': typeof ApiPosthogSplatServerRoute
  '/api/trpc/$': typeof ApiTrpcSplatServerRoute
}
export interface FileServerRoutesById {
  __root__: typeof rootServerRouteImport
  '/api/auth/$': typeof ApiAuthSplatServerRoute
  '/api/openapi/$': typeof ApiOpenapiSplatServerRoute
  '/api/posthog/$': typeof ApiPosthogSplatServerRoute
  '/api/trpc/$': typeof ApiTrpcSplatServerRoute
}
export interface FileServerRouteTypes {
  fileServerRoutesByFullPath: FileServerRoutesByFullPath
  fullPaths: '/api/auth/$' | '/api/openapi/$' | '/api/posthog/$' | '/api/trpc/$'
  fileServerRoutesByTo: FileServerRoutesByTo
  to: '/api/auth/$' | '/api/openapi/$' | '/api/posthog/$' | '/api/trpc/$'
  id:
    | '__root__'
    | '/api/auth/$'
    | '/api/openapi/$'
    | '/api/posthog/$'
    | '/api/trpc/$'
  fileServerRoutesById: FileServerRoutesById
}
export interface RootServerRouteChildren {
  ApiAuthSplatServerRoute: typeof ApiAuthSplatServerRoute
  ApiOpenapiSplatServerRoute: typeof ApiOpenapiSplatServerRoute
  ApiPosthogSplatServerRoute: typeof ApiPosthogSplatServerRoute
  ApiTrpcSplatServerRoute: typeof ApiTrpcSplatServerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/catalogue': {
      id: '/catalogue'
      path: '/catalogue'
      fullPath: '/catalogue'
      preLoaderRoute: typeof CatalogueLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations/': {
      id: '/organizations/'
      path: '/organizations'
      fullPath: '/organizations'
      preLoaderRoute: typeof OrganizationsIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$slug': {
      id: '/projects/$slug'
      path: '/projects/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof ProjectsSlugLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations/$slug': {
      id: '/organizations/$slug'
      path: '/organizations/$slug'
      fullPath: '/organizations/$slug'
      preLoaderRoute: typeof OrganizationsSlugLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/$': {
      id: '/settings/$'
      path: '/settings/$'
      fullPath: '/settings/$'
      preLoaderRoute: typeof SettingsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/preference/$': {
      id: '/settings/preference/$'
      path: '/settings/preference/$'
      fullPath: '/settings/preference/$'
      preLoaderRoute: typeof SettingsPreferenceSplatLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/keys/$': {
      id: '/settings/keys/$'
      path: '/settings/keys/$'
      fullPath: '/settings/keys/$'
      preLoaderRoute: typeof SettingsKeysSplatLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/credits/$': {
      id: '/settings/credits/$'
      path: '/settings/credits/$'
      fullPath: '/settings/credits/$'
      preLoaderRoute: typeof SettingsCreditsSplatLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/activity/$': {
      id: '/settings/activity/$'
      path: '/settings/activity/$'
      fullPath: '/settings/activity/$'
      preLoaderRoute: typeof SettingsActivitySplatLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$slug/view/$version': {
      id: '/projects/$slug/view/$version'
      path: '/view/$version'
      fullPath: '/projects/$slug/view/$version'
      preLoaderRoute: typeof ProjectsSlugViewVersionLazyRouteImport
      parentRoute: typeof ProjectsSlugLazyRoute
    }
  }
}
declare module '@tanstack/react-start/server' {
  interface ServerFileRoutesByPath {
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/posthog/$': {
      id: '/api/posthog/$'
      path: '/api/posthog/$'
      fullPath: '/api/posthog/$'
      preLoaderRoute: typeof ApiPosthogSplatServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/openapi/$': {
      id: '/api/openapi/$'
      path: '/api/openapi/$'
      fullPath: '/api/openapi/$'
      preLoaderRoute: typeof ApiOpenapiSplatServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
  }
}

interface ProjectsSlugLazyRouteChildren {
  ProjectsSlugViewVersionLazyRoute: typeof ProjectsSlugViewVersionLazyRoute
}

const ProjectsSlugLazyRouteChildren: ProjectsSlugLazyRouteChildren = {
  ProjectsSlugViewVersionLazyRoute: ProjectsSlugViewVersionLazyRoute,
}

const ProjectsSlugLazyRouteWithChildren =
  ProjectsSlugLazyRoute._addFileChildren(ProjectsSlugLazyRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  CatalogueLazyRoute: CatalogueLazyRoute,
  SettingsSplatRoute: SettingsSplatRoute,
  OrganizationsSlugLazyRoute: OrganizationsSlugLazyRoute,
  ProjectsSlugLazyRoute: ProjectsSlugLazyRouteWithChildren,
  OrganizationsIndexLazyRoute: OrganizationsIndexLazyRoute,
  ProjectsIndexLazyRoute: ProjectsIndexLazyRoute,
  SettingsActivitySplatLazyRoute: SettingsActivitySplatLazyRoute,
  SettingsCreditsSplatLazyRoute: SettingsCreditsSplatLazyRoute,
  SettingsKeysSplatLazyRoute: SettingsKeysSplatLazyRoute,
  SettingsPreferenceSplatLazyRoute: SettingsPreferenceSplatLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
const rootServerRouteChildren: RootServerRouteChildren = {
  ApiAuthSplatServerRoute: ApiAuthSplatServerRoute,
  ApiOpenapiSplatServerRoute: ApiOpenapiSplatServerRoute,
  ApiPosthogSplatServerRoute: ApiPosthogSplatServerRoute,
  ApiTrpcSplatServerRoute: ApiTrpcSplatServerRoute,
}
export const serverRouteTree = rootServerRouteImport
  ._addFileChildren(rootServerRouteChildren)
  ._addFileTypes<FileServerRouteTypes>()
