/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'
import { createServerRootRoute } from '@tanstack/react-start/server'

import { Route as rootRouteImport } from './routes/__root'
import { Route as PricingIndexRouteImport } from './routes/pricing/index'
import { Route as SettingsSplatRouteImport } from './routes/settings/$'
import { Route as AuthVerifyEmailRouteImport } from './routes/auth/verify-email'
import { Route as AuthTwoFactorAuthRouteImport } from './routes/auth/two-factor-auth'
import { Route as AuthSignUpRouteImport } from './routes/auth/sign-up'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as AuthSentEmailRouteImport } from './routes/auth/sent-email'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AuthChangePasswordRouteImport } from './routes/auth/change-password'
import { Route as InternalSessionTestRouteImport } from './routes/$internal/session-test'
import { ServerRoute as InternalEmailTemplatesPreviewServerRouteImport } from './routes/$internal/email-templates-preview'
import { ServerRoute as ApiTrpcSplatServerRouteImport } from './routes/api/trpc/$'
import { ServerRoute as ApiPosthogSplatServerRouteImport } from './routes/api/posthog/$'
import { ServerRoute as ApiOpenapiSplatServerRouteImport } from './routes/api/openapi/$'
import { ServerRoute as ApiCapSplatServerRouteImport } from './routes/api/cap/$'
import { ServerRoute as ApiAuthSetPasswordServerRouteImport } from './routes/api/auth/set-password'
import { ServerRoute as ApiAuthSplatServerRouteImport } from './routes/api/auth/$'

const CatalogueLazyRouteImport = createFileRoute('/catalogue')()
const IndexLazyRouteImport = createFileRoute('/')()
const ProjectsIndexLazyRouteImport = createFileRoute('/projects/')()
const OrganizationsIndexLazyRouteImport = createFileRoute('/organizations/')()
const ProjectsSlugLazyRouteImport = createFileRoute('/projects/$slug')()
const OrganizationsSlugLazyRouteImport = createFileRoute(
  '/organizations/$slug',
)()
const SettingsPreferenceSplatLazyRouteImport = createFileRoute(
  '/settings/preference/$',
)()
const SettingsKeysSplatLazyRouteImport = createFileRoute('/settings/keys/$')()
const SettingsCreditsSplatLazyRouteImport = createFileRoute(
  '/settings/credits/$',
)()
const SettingsActivitySplatLazyRouteImport = createFileRoute(
  '/settings/activity/$',
)()
const ProjectsSlugViewVersionLazyRouteImport = createFileRoute(
  '/projects/$slug/view/$version',
)()
const rootServerRouteImport = createServerRootRoute()

const CatalogueLazyRoute = CatalogueLazyRouteImport.update({
  id: '/catalogue',
  path: '/catalogue',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/catalogue.lazy').then((d) => d.Route))
const IndexLazyRoute = IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const ProjectsIndexLazyRoute = ProjectsIndexLazyRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/projects/index.lazy').then((d) => d.Route),
)
const OrganizationsIndexLazyRoute = OrganizationsIndexLazyRouteImport.update({
  id: '/organizations/',
  path: '/organizations/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/organizations/index.lazy').then((d) => d.Route),
)
const PricingIndexRoute = PricingIndexRouteImport.update({
  id: '/pricing/',
  path: '/pricing/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsSlugLazyRoute = ProjectsSlugLazyRouteImport.update({
  id: '/projects/$slug',
  path: '/projects/$slug',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/projects/$slug.lazy').then((d) => d.Route),
)
const OrganizationsSlugLazyRoute = OrganizationsSlugLazyRouteImport.update({
  id: '/organizations/$slug',
  path: '/organizations/$slug',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/organizations/$slug.lazy').then((d) => d.Route),
)
const SettingsSplatRoute = SettingsSplatRouteImport.update({
  id: '/settings/$',
  path: '/settings/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyEmailRoute = AuthVerifyEmailRouteImport.update({
  id: '/auth/verify-email',
  path: '/auth/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthTwoFactorAuthRoute = AuthTwoFactorAuthRouteImport.update({
  id: '/auth/two-factor-auth',
  path: '/auth/two-factor-auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/auth/sign-up',
  path: '/auth/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSentEmailRoute = AuthSentEmailRouteImport.update({
  id: '/auth/sent-email',
  path: '/auth/sent-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthChangePasswordRoute = AuthChangePasswordRouteImport.update({
  id: '/auth/change-password',
  path: '/auth/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const InternalSessionTestRoute = InternalSessionTestRouteImport.update({
  id: '/$internal/session-test',
  path: '/$internal/session-test',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsPreferenceSplatLazyRoute =
  SettingsPreferenceSplatLazyRouteImport.update({
    id: '/settings/preference/$',
    path: '/settings/preference/$',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/settings/preference/$.lazy').then((d) => d.Route),
  )
const SettingsKeysSplatLazyRoute = SettingsKeysSplatLazyRouteImport.update({
  id: '/settings/keys/$',
  path: '/settings/keys/$',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/settings/keys/$.lazy').then((d) => d.Route),
)
const SettingsCreditsSplatLazyRoute =
  SettingsCreditsSplatLazyRouteImport.update({
    id: '/settings/credits/$',
    path: '/settings/credits/$',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/settings/credits/$.lazy').then((d) => d.Route),
  )
const SettingsActivitySplatLazyRoute =
  SettingsActivitySplatLazyRouteImport.update({
    id: '/settings/activity/$',
    path: '/settings/activity/$',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/settings/activity/$.lazy').then((d) => d.Route),
  )
const ProjectsSlugViewVersionLazyRoute =
  ProjectsSlugViewVersionLazyRouteImport.update({
    id: '/view/$version',
    path: '/view/$version',
    getParentRoute: () => ProjectsSlugLazyRoute,
  } as any).lazy(() =>
    import('./routes/projects/$slug/view/$version.lazy').then((d) => d.Route),
  )
const InternalEmailTemplatesPreviewServerRoute =
  InternalEmailTemplatesPreviewServerRouteImport.update({
    id: '/$internal/email-templates-preview',
    path: '/$internal/email-templates-preview',
    getParentRoute: () => rootServerRouteImport,
  } as any)
const ApiTrpcSplatServerRoute = ApiTrpcSplatServerRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiPosthogSplatServerRoute = ApiPosthogSplatServerRouteImport.update({
  id: '/api/posthog/$',
  path: '/api/posthog/$',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiOpenapiSplatServerRoute = ApiOpenapiSplatServerRouteImport.update({
  id: '/api/openapi/$',
  path: '/api/openapi/$',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiCapSplatServerRoute = ApiCapSplatServerRouteImport.update({
  id: '/api/cap/$',
  path: '/api/cap/$',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiAuthSetPasswordServerRoute =
  ApiAuthSetPasswordServerRouteImport.update({
    id: '/api/auth/set-password',
    path: '/api/auth/set-password',
    getParentRoute: () => rootServerRouteImport,
  } as any)
const ApiAuthSplatServerRoute = ApiAuthSplatServerRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootServerRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/catalogue': typeof CatalogueLazyRoute
  '/$internal/session-test': typeof InternalSessionTestRoute
  '/auth/change-password': typeof AuthChangePasswordRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sent-email': typeof AuthSentEmailRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth/two-factor-auth': typeof AuthTwoFactorAuthRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/settings/$': typeof SettingsSplatRoute
  '/organizations/$slug': typeof OrganizationsSlugLazyRoute
  '/projects/$slug': typeof ProjectsSlugLazyRouteWithChildren
  '/pricing': typeof PricingIndexRoute
  '/organizations': typeof OrganizationsIndexLazyRoute
  '/projects': typeof ProjectsIndexLazyRoute
  '/settings/activity/$': typeof SettingsActivitySplatLazyRoute
  '/settings/credits/$': typeof SettingsCreditsSplatLazyRoute
  '/settings/keys/$': typeof SettingsKeysSplatLazyRoute
  '/settings/preference/$': typeof SettingsPreferenceSplatLazyRoute
  '/projects/$slug/view/$version': typeof ProjectsSlugViewVersionLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/catalogue': typeof CatalogueLazyRoute
  '/$internal/session-test': typeof InternalSessionTestRoute
  '/auth/change-password': typeof AuthChangePasswordRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sent-email': typeof AuthSentEmailRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth/two-factor-auth': typeof AuthTwoFactorAuthRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/settings/$': typeof SettingsSplatRoute
  '/organizations/$slug': typeof OrganizationsSlugLazyRoute
  '/projects/$slug': typeof ProjectsSlugLazyRouteWithChildren
  '/pricing': typeof PricingIndexRoute
  '/organizations': typeof OrganizationsIndexLazyRoute
  '/projects': typeof ProjectsIndexLazyRoute
  '/settings/activity/$': typeof SettingsActivitySplatLazyRoute
  '/settings/credits/$': typeof SettingsCreditsSplatLazyRoute
  '/settings/keys/$': typeof SettingsKeysSplatLazyRoute
  '/settings/preference/$': typeof SettingsPreferenceSplatLazyRoute
  '/projects/$slug/view/$version': typeof ProjectsSlugViewVersionLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexLazyRoute
  '/catalogue': typeof CatalogueLazyRoute
  '/$internal/session-test': typeof InternalSessionTestRoute
  '/auth/change-password': typeof AuthChangePasswordRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sent-email': typeof AuthSentEmailRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth/two-factor-auth': typeof AuthTwoFactorAuthRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/settings/$': typeof SettingsSplatRoute
  '/organizations/$slug': typeof OrganizationsSlugLazyRoute
  '/projects/$slug': typeof ProjectsSlugLazyRouteWithChildren
  '/pricing/': typeof PricingIndexRoute
  '/organizations/': typeof OrganizationsIndexLazyRoute
  '/projects/': typeof ProjectsIndexLazyRoute
  '/settings/activity/$': typeof SettingsActivitySplatLazyRoute
  '/settings/credits/$': typeof SettingsCreditsSplatLazyRoute
  '/settings/keys/$': typeof SettingsKeysSplatLazyRoute
  '/settings/preference/$': typeof SettingsPreferenceSplatLazyRoute
  '/projects/$slug/view/$version': typeof ProjectsSlugViewVersionLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/catalogue'
    | '/$internal/session-test'
    | '/auth/change-password'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/auth/sent-email'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/auth/two-factor-auth'
    | '/auth/verify-email'
    | '/settings/$'
    | '/organizations/$slug'
    | '/projects/$slug'
    | '/pricing'
    | '/organizations'
    | '/projects'
    | '/settings/activity/$'
    | '/settings/credits/$'
    | '/settings/keys/$'
    | '/settings/preference/$'
    | '/projects/$slug/view/$version'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/catalogue'
    | '/$internal/session-test'
    | '/auth/change-password'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/auth/sent-email'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/auth/two-factor-auth'
    | '/auth/verify-email'
    | '/settings/$'
    | '/organizations/$slug'
    | '/projects/$slug'
    | '/pricing'
    | '/organizations'
    | '/projects'
    | '/settings/activity/$'
    | '/settings/credits/$'
    | '/settings/keys/$'
    | '/settings/preference/$'
    | '/projects/$slug/view/$version'
  id:
    | '__root__'
    | '/'
    | '/catalogue'
    | '/$internal/session-test'
    | '/auth/change-password'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/auth/sent-email'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/auth/two-factor-auth'
    | '/auth/verify-email'
    | '/settings/$'
    | '/organizations/$slug'
    | '/projects/$slug'
    | '/pricing/'
    | '/organizations/'
    | '/projects/'
    | '/settings/activity/$'
    | '/settings/credits/$'
    | '/settings/keys/$'
    | '/settings/preference/$'
    | '/projects/$slug/view/$version'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  CatalogueLazyRoute: typeof CatalogueLazyRoute
  InternalSessionTestRoute: typeof InternalSessionTestRoute
  AuthChangePasswordRoute: typeof AuthChangePasswordRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSentEmailRoute: typeof AuthSentEmailRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  AuthTwoFactorAuthRoute: typeof AuthTwoFactorAuthRoute
  AuthVerifyEmailRoute: typeof AuthVerifyEmailRoute
  SettingsSplatRoute: typeof SettingsSplatRoute
  OrganizationsSlugLazyRoute: typeof OrganizationsSlugLazyRoute
  ProjectsSlugLazyRoute: typeof ProjectsSlugLazyRouteWithChildren
  PricingIndexRoute: typeof PricingIndexRoute
  OrganizationsIndexLazyRoute: typeof OrganizationsIndexLazyRoute
  ProjectsIndexLazyRoute: typeof ProjectsIndexLazyRoute
  SettingsActivitySplatLazyRoute: typeof SettingsActivitySplatLazyRoute
  SettingsCreditsSplatLazyRoute: typeof SettingsCreditsSplatLazyRoute
  SettingsKeysSplatLazyRoute: typeof SettingsKeysSplatLazyRoute
  SettingsPreferenceSplatLazyRoute: typeof SettingsPreferenceSplatLazyRoute
}
export interface FileServerRoutesByFullPath {
  '/$internal/email-templates-preview': typeof InternalEmailTemplatesPreviewServerRoute
  '/api/auth/$': typeof ApiAuthSplatServerRoute
  '/api/auth/set-password': typeof ApiAuthSetPasswordServerRoute
  '/api/cap/$': typeof ApiCapSplatServerRoute
  '/api/openapi/$': typeof ApiOpenapiSplatServerRoute
  '/api/posthog/$': typeof ApiPosthogSplatServerRoute
  '/api/trpc/$': typeof ApiTrpcSplatServerRoute
}
export interface FileServerRoutesByTo {
  '/$internal/email-templates-preview': typeof InternalEmailTemplatesPreviewServerRoute
  '/api/auth/$': typeof ApiAuthSplatServerRoute
  '/api/auth/set-password': typeof ApiAuthSetPasswordServerRoute
  '/api/cap/$': typeof ApiCapSplatServerRoute
  '/api/openapi/$': typeof ApiOpenapiSplatServerRoute
  '/api/posthog/$': typeof ApiPosthogSplatServerRoute
  '/api/trpc/$': typeof ApiTrpcSplatServerRoute
}
export interface FileServerRoutesById {
  __root__: typeof rootServerRouteImport
  '/$internal/email-templates-preview': typeof InternalEmailTemplatesPreviewServerRoute
  '/api/auth/$': typeof ApiAuthSplatServerRoute
  '/api/auth/set-password': typeof ApiAuthSetPasswordServerRoute
  '/api/cap/$': typeof ApiCapSplatServerRoute
  '/api/openapi/$': typeof ApiOpenapiSplatServerRoute
  '/api/posthog/$': typeof ApiPosthogSplatServerRoute
  '/api/trpc/$': typeof ApiTrpcSplatServerRoute
}
export interface FileServerRouteTypes {
  fileServerRoutesByFullPath: FileServerRoutesByFullPath
  fullPaths:
    | '/$internal/email-templates-preview'
    | '/api/auth/$'
    | '/api/auth/set-password'
    | '/api/cap/$'
    | '/api/openapi/$'
    | '/api/posthog/$'
    | '/api/trpc/$'
  fileServerRoutesByTo: FileServerRoutesByTo
  to:
    | '/$internal/email-templates-preview'
    | '/api/auth/$'
    | '/api/auth/set-password'
    | '/api/cap/$'
    | '/api/openapi/$'
    | '/api/posthog/$'
    | '/api/trpc/$'
  id:
    | '__root__'
    | '/$internal/email-templates-preview'
    | '/api/auth/$'
    | '/api/auth/set-password'
    | '/api/cap/$'
    | '/api/openapi/$'
    | '/api/posthog/$'
    | '/api/trpc/$'
  fileServerRoutesById: FileServerRoutesById
}
export interface RootServerRouteChildren {
  InternalEmailTemplatesPreviewServerRoute: typeof InternalEmailTemplatesPreviewServerRoute
  ApiAuthSplatServerRoute: typeof ApiAuthSplatServerRoute
  ApiAuthSetPasswordServerRoute: typeof ApiAuthSetPasswordServerRoute
  ApiCapSplatServerRoute: typeof ApiCapSplatServerRoute
  ApiOpenapiSplatServerRoute: typeof ApiOpenapiSplatServerRoute
  ApiPosthogSplatServerRoute: typeof ApiPosthogSplatServerRoute
  ApiTrpcSplatServerRoute: typeof ApiTrpcSplatServerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/catalogue': {
      id: '/catalogue'
      path: '/catalogue'
      fullPath: '/catalogue'
      preLoaderRoute: typeof CatalogueLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations/': {
      id: '/organizations/'
      path: '/organizations'
      fullPath: '/organizations'
      preLoaderRoute: typeof OrganizationsIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing/': {
      id: '/pricing/'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$slug': {
      id: '/projects/$slug'
      path: '/projects/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof ProjectsSlugLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations/$slug': {
      id: '/organizations/$slug'
      path: '/organizations/$slug'
      fullPath: '/organizations/$slug'
      preLoaderRoute: typeof OrganizationsSlugLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/$': {
      id: '/settings/$'
      path: '/settings/$'
      fullPath: '/settings/$'
      preLoaderRoute: typeof SettingsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verify-email': {
      id: '/auth/verify-email'
      path: '/auth/verify-email'
      fullPath: '/auth/verify-email'
      preLoaderRoute: typeof AuthVerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/two-factor-auth': {
      id: '/auth/two-factor-auth'
      path: '/auth/two-factor-auth'
      fullPath: '/auth/two-factor-auth'
      preLoaderRoute: typeof AuthTwoFactorAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/auth/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sent-email': {
      id: '/auth/sent-email'
      path: '/auth/sent-email'
      fullPath: '/auth/sent-email'
      preLoaderRoute: typeof AuthSentEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/change-password': {
      id: '/auth/change-password'
      path: '/auth/change-password'
      fullPath: '/auth/change-password'
      preLoaderRoute: typeof AuthChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$internal/session-test': {
      id: '/$internal/session-test'
      path: '/$internal/session-test'
      fullPath: '/$internal/session-test'
      preLoaderRoute: typeof InternalSessionTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/preference/$': {
      id: '/settings/preference/$'
      path: '/settings/preference/$'
      fullPath: '/settings/preference/$'
      preLoaderRoute: typeof SettingsPreferenceSplatLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/keys/$': {
      id: '/settings/keys/$'
      path: '/settings/keys/$'
      fullPath: '/settings/keys/$'
      preLoaderRoute: typeof SettingsKeysSplatLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/credits/$': {
      id: '/settings/credits/$'
      path: '/settings/credits/$'
      fullPath: '/settings/credits/$'
      preLoaderRoute: typeof SettingsCreditsSplatLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/activity/$': {
      id: '/settings/activity/$'
      path: '/settings/activity/$'
      fullPath: '/settings/activity/$'
      preLoaderRoute: typeof SettingsActivitySplatLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$slug/view/$version': {
      id: '/projects/$slug/view/$version'
      path: '/view/$version'
      fullPath: '/projects/$slug/view/$version'
      preLoaderRoute: typeof ProjectsSlugViewVersionLazyRouteImport
      parentRoute: typeof ProjectsSlugLazyRoute
    }
  }
}
declare module '@tanstack/react-start/server' {
  interface ServerFileRoutesByPath {
    '/$internal/email-templates-preview': {
      id: '/$internal/email-templates-preview'
      path: '/$internal/email-templates-preview'
      fullPath: '/$internal/email-templates-preview'
      preLoaderRoute: typeof InternalEmailTemplatesPreviewServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/posthog/$': {
      id: '/api/posthog/$'
      path: '/api/posthog/$'
      fullPath: '/api/posthog/$'
      preLoaderRoute: typeof ApiPosthogSplatServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/openapi/$': {
      id: '/api/openapi/$'
      path: '/api/openapi/$'
      fullPath: '/api/openapi/$'
      preLoaderRoute: typeof ApiOpenapiSplatServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/cap/$': {
      id: '/api/cap/$'
      path: '/api/cap/$'
      fullPath: '/api/cap/$'
      preLoaderRoute: typeof ApiCapSplatServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/auth/set-password': {
      id: '/api/auth/set-password'
      path: '/api/auth/set-password'
      fullPath: '/api/auth/set-password'
      preLoaderRoute: typeof ApiAuthSetPasswordServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
  }
}

interface ProjectsSlugLazyRouteChildren {
  ProjectsSlugViewVersionLazyRoute: typeof ProjectsSlugViewVersionLazyRoute
}

const ProjectsSlugLazyRouteChildren: ProjectsSlugLazyRouteChildren = {
  ProjectsSlugViewVersionLazyRoute: ProjectsSlugViewVersionLazyRoute,
}

const ProjectsSlugLazyRouteWithChildren =
  ProjectsSlugLazyRoute._addFileChildren(ProjectsSlugLazyRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  CatalogueLazyRoute: CatalogueLazyRoute,
  InternalSessionTestRoute: InternalSessionTestRoute,
  AuthChangePasswordRoute: AuthChangePasswordRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSentEmailRoute: AuthSentEmailRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  AuthTwoFactorAuthRoute: AuthTwoFactorAuthRoute,
  AuthVerifyEmailRoute: AuthVerifyEmailRoute,
  SettingsSplatRoute: SettingsSplatRoute,
  OrganizationsSlugLazyRoute: OrganizationsSlugLazyRoute,
  ProjectsSlugLazyRoute: ProjectsSlugLazyRouteWithChildren,
  PricingIndexRoute: PricingIndexRoute,
  OrganizationsIndexLazyRoute: OrganizationsIndexLazyRoute,
  ProjectsIndexLazyRoute: ProjectsIndexLazyRoute,
  SettingsActivitySplatLazyRoute: SettingsActivitySplatLazyRoute,
  SettingsCreditsSplatLazyRoute: SettingsCreditsSplatLazyRoute,
  SettingsKeysSplatLazyRoute: SettingsKeysSplatLazyRoute,
  SettingsPreferenceSplatLazyRoute: SettingsPreferenceSplatLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
const rootServerRouteChildren: RootServerRouteChildren = {
  InternalEmailTemplatesPreviewServerRoute:
    InternalEmailTemplatesPreviewServerRoute,
  ApiAuthSplatServerRoute: ApiAuthSplatServerRoute,
  ApiAuthSetPasswordServerRoute: ApiAuthSetPasswordServerRoute,
  ApiCapSplatServerRoute: ApiCapSplatServerRoute,
  ApiOpenapiSplatServerRoute: ApiOpenapiSplatServerRoute,
  ApiPosthogSplatServerRoute: ApiPosthogSplatServerRoute,
  ApiTrpcSplatServerRoute: ApiTrpcSplatServerRoute,
}
export const serverRouteTree = rootServerRouteImport
  ._addFileChildren(rootServerRouteChildren)
  ._addFileTypes<FileServerRouteTypes>()
