/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as McpSplatRouteImport } from './routes/mcp/$'
import { Route as AuthVerifyEmailRouteImport } from './routes/auth/verify-email'
import { Route as AuthTwoFactorVerifyRouteImport } from './routes/auth/two-factor-verify'
import { Route as AuthTwoFactorAuthRouteImport } from './routes/auth/two-factor-auth'
import { Route as AuthSignUpRouteImport } from './routes/auth/sign-up'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as AuthSentEmailRouteImport } from './routes/auth/sent-email'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AuthChangePasswordRouteImport } from './routes/auth/change-password'
import { Route as AppOrganizationsRouteImport } from './routes/app/organizations'
import { Route as AppInvitationsRouteImport } from './routes/app/invitations'
import { Route as AppDashboardRouteImport } from './routes/app/dashboard'
import { Route as AppCatalogueRouteImport } from './routes/app/catalogue'
import { Route as InternalImageUploadTestRouteImport } from './routes/$internal/image-upload-test'
import { Route as InternalEmailTemplatesPreviewRouteImport } from './routes/$internal/email-templates-preview'
import { Route as InternalConfirmTestRouteImport } from './routes/$internal/confirm-test'
import { Route as AppSettingsIndexRouteImport } from './routes/app/settings/index'
import { Route as AppOrganizationsIndexRouteImport } from './routes/app/organizations/index'
import { Route as AppSettingsPreferenceRouteImport } from './routes/app/settings/preference'
import { Route as AppSettingsKeysRouteImport } from './routes/app/settings/keys'
import { Route as AppSettingsCreditsRouteImport } from './routes/app/settings/credits'
import { Route as AppSettingsActivityRouteImport } from './routes/app/settings/activity'
import { Route as AppOrganizationsChar126RouteImport } from './routes/app/organizations/~'
import { Route as AppOrganizationsCreateRouteImport } from './routes/app/organizations/create'
import { Route as AppOrganizationsOrganizationSlugRouteImport } from './routes/app/organizations/$organizationSlug'
import { Route as ApiTrpcSplatRouteImport } from './routes/api/trpc/$'
import { Route as ApiProxySplatRouteImport } from './routes/api/proxy/$'
import { Route as ApiPosthogSplatRouteImport } from './routes/api/posthog/$'
import { Route as ApiPolarWebhookRouteImport } from './routes/api/polar/webhook'
import { Route as ApiOpenapiSplatRouteImport } from './routes/api/openapi/$'
import { Route as ApiCreditsSplatRouteImport } from './routes/api/credits/$'
import { Route as ApiCapSplatRouteImport } from './routes/api/cap/$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AppOrganizationsOrganizationSlugIndexRouteImport } from './routes/app/organizations/$organizationSlug/index'
import { Route as AppSettingsCreditsSuccessRouteImport } from './routes/app/settings/credits/success'
import { Route as AppOrganizationsOrganizationSlugSettingsRouteImport } from './routes/app/organizations/$organizationSlug/settings'
import { Route as AppOrganizationsOrganizationSlugProjectsRouteImport } from './routes/app/organizations/$organizationSlug/projects'
import { Route as AppOrganizationsOrganizationSlugProjectsIndexRouteImport } from './routes/app/organizations/$organizationSlug/projects/index'
import { Route as AppOrganizationsOrganizationSlugProjectsChar126RouteImport } from './routes/app/organizations/$organizationSlug/projects/~'
import { Route as AppOrganizationsOrganizationSlugProjectsCreateRouteImport } from './routes/app/organizations/$organizationSlug/projects/create'
import { Route as ApiProjectsOrganizationSlugProjectSlugOpenapiRouteImport } from './routes/api/projects/$organizationSlug/$projectSlug/openapi'
import { Route as AppOrganizationsOrganizationSlugProjectsProjectSlugIndexRouteImport } from './routes/app/organizations/$organizationSlug/projects/$projectSlug/index'
import { Route as AppOrganizationsOrganizationSlugProjectsProjectSlugSpecRouteImport } from './routes/app/organizations/$organizationSlug/projects/$projectSlug/spec'
import { Route as AppOrganizationsOrganizationSlugProjectsProjectSlugExplorerRouteImport } from './routes/app/organizations/$organizationSlug/projects/$projectSlug/explorer'

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const McpSplatRoute = McpSplatRouteImport.update({
  id: '/mcp/$',
  path: '/mcp/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyEmailRoute = AuthVerifyEmailRouteImport.update({
  id: '/auth/verify-email',
  path: '/auth/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthTwoFactorVerifyRoute = AuthTwoFactorVerifyRouteImport.update({
  id: '/auth/two-factor-verify',
  path: '/auth/two-factor-verify',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthTwoFactorAuthRoute = AuthTwoFactorAuthRouteImport.update({
  id: '/auth/two-factor-auth',
  path: '/auth/two-factor-auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/auth/sign-up',
  path: '/auth/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSentEmailRoute = AuthSentEmailRouteImport.update({
  id: '/auth/sent-email',
  path: '/auth/sent-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthChangePasswordRoute = AuthChangePasswordRouteImport.update({
  id: '/auth/change-password',
  path: '/auth/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppOrganizationsRoute = AppOrganizationsRouteImport.update({
  id: '/organizations',
  path: '/organizations',
  getParentRoute: () => AppRoute,
} as any)
const AppInvitationsRoute = AppInvitationsRouteImport.update({
  id: '/invitations',
  path: '/invitations',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCatalogueRoute = AppCatalogueRouteImport.update({
  id: '/catalogue',
  path: '/catalogue',
  getParentRoute: () => AppRoute,
} as any)
const InternalImageUploadTestRoute = InternalImageUploadTestRouteImport.update({
  id: '/$internal/image-upload-test',
  path: '/$internal/image-upload-test',
  getParentRoute: () => rootRouteImport,
} as any)
const InternalEmailTemplatesPreviewRoute =
  InternalEmailTemplatesPreviewRouteImport.update({
    id: '/$internal/email-templates-preview',
    path: '/$internal/email-templates-preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const InternalConfirmTestRoute = InternalConfirmTestRouteImport.update({
  id: '/$internal/confirm-test',
  path: '/$internal/confirm-test',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AppRoute,
} as any)
const AppOrganizationsIndexRoute = AppOrganizationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppOrganizationsRoute,
} as any)
const AppSettingsPreferenceRoute = AppSettingsPreferenceRouteImport.update({
  id: '/settings/preference',
  path: '/settings/preference',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsKeysRoute = AppSettingsKeysRouteImport.update({
  id: '/settings/keys',
  path: '/settings/keys',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsCreditsRoute = AppSettingsCreditsRouteImport.update({
  id: '/settings/credits',
  path: '/settings/credits',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsActivityRoute = AppSettingsActivityRouteImport.update({
  id: '/settings/activity',
  path: '/settings/activity',
  getParentRoute: () => AppRoute,
} as any)
const AppOrganizationsChar126Route = AppOrganizationsChar126RouteImport.update({
  id: '/~',
  path: '/~',
  getParentRoute: () => AppOrganizationsRoute,
} as any)
const AppOrganizationsCreateRoute = AppOrganizationsCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AppOrganizationsRoute,
} as any)
const AppOrganizationsOrganizationSlugRoute =
  AppOrganizationsOrganizationSlugRouteImport.update({
    id: '/$organizationSlug',
    path: '/$organizationSlug',
    getParentRoute: () => AppOrganizationsRoute,
  } as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProxySplatRoute = ApiProxySplatRouteImport.update({
  id: '/api/proxy/$',
  path: '/api/proxy/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPosthogSplatRoute = ApiPosthogSplatRouteImport.update({
  id: '/api/posthog/$',
  path: '/api/posthog/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPolarWebhookRoute = ApiPolarWebhookRouteImport.update({
  id: '/api/polar/webhook',
  path: '/api/polar/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOpenapiSplatRoute = ApiOpenapiSplatRouteImport.update({
  id: '/api/openapi/$',
  path: '/api/openapi/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCreditsSplatRoute = ApiCreditsSplatRouteImport.update({
  id: '/api/credits/$',
  path: '/api/credits/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCapSplatRoute = ApiCapSplatRouteImport.update({
  id: '/api/cap/$',
  path: '/api/cap/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppOrganizationsOrganizationSlugIndexRoute =
  AppOrganizationsOrganizationSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppOrganizationsOrganizationSlugRoute,
  } as any)
const AppSettingsCreditsSuccessRoute =
  AppSettingsCreditsSuccessRouteImport.update({
    id: '/success',
    path: '/success',
    getParentRoute: () => AppSettingsCreditsRoute,
  } as any)
const AppOrganizationsOrganizationSlugSettingsRoute =
  AppOrganizationsOrganizationSlugSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AppOrganizationsOrganizationSlugRoute,
  } as any)
const AppOrganizationsOrganizationSlugProjectsRoute =
  AppOrganizationsOrganizationSlugProjectsRouteImport.update({
    id: '/projects',
    path: '/projects',
    getParentRoute: () => AppOrganizationsOrganizationSlugRoute,
  } as any)
const AppOrganizationsOrganizationSlugProjectsIndexRoute =
  AppOrganizationsOrganizationSlugProjectsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppOrganizationsOrganizationSlugProjectsRoute,
  } as any)
const AppOrganizationsOrganizationSlugProjectsChar126Route =
  AppOrganizationsOrganizationSlugProjectsChar126RouteImport.update({
    id: '/~',
    path: '/~',
    getParentRoute: () => AppOrganizationsOrganizationSlugProjectsRoute,
  } as any)
const AppOrganizationsOrganizationSlugProjectsCreateRoute =
  AppOrganizationsOrganizationSlugProjectsCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => AppOrganizationsOrganizationSlugProjectsRoute,
  } as any)
const ApiProjectsOrganizationSlugProjectSlugOpenapiRoute =
  ApiProjectsOrganizationSlugProjectSlugOpenapiRouteImport.update({
    id: '/api/projects/$organizationSlug/$projectSlug/openapi',
    path: '/api/projects/$organizationSlug/$projectSlug/openapi',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppOrganizationsOrganizationSlugProjectsProjectSlugIndexRoute =
  AppOrganizationsOrganizationSlugProjectsProjectSlugIndexRouteImport.update({
    id: '/$projectSlug/',
    path: '/$projectSlug/',
    getParentRoute: () => AppOrganizationsOrganizationSlugProjectsRoute,
  } as any)
const AppOrganizationsOrganizationSlugProjectsProjectSlugSpecRoute =
  AppOrganizationsOrganizationSlugProjectsProjectSlugSpecRouteImport.update({
    id: '/$projectSlug/spec',
    path: '/$projectSlug/spec',
    getParentRoute: () => AppOrganizationsOrganizationSlugProjectsRoute,
  } as any)
const AppOrganizationsOrganizationSlugProjectsProjectSlugExplorerRoute =
  AppOrganizationsOrganizationSlugProjectsProjectSlugExplorerRouteImport.update(
    {
      id: '/$projectSlug/explorer',
      path: '/$projectSlug/explorer',
      getParentRoute: () => AppOrganizationsOrganizationSlugProjectsRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/$internal/confirm-test': typeof InternalConfirmTestRoute
  '/$internal/email-templates-preview': typeof InternalEmailTemplatesPreviewRoute
  '/$internal/image-upload-test': typeof InternalImageUploadTestRoute
  '/app/catalogue': typeof AppCatalogueRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/invitations': typeof AppInvitationsRoute
  '/app/organizations': typeof AppOrganizationsRouteWithChildren
  '/auth/change-password': typeof AuthChangePasswordRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sent-email': typeof AuthSentEmailRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth/two-factor-auth': typeof AuthTwoFactorAuthRoute
  '/auth/two-factor-verify': typeof AuthTwoFactorVerifyRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/mcp/$': typeof McpSplatRoute
  '/app/': typeof AppIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cap/$': typeof ApiCapSplatRoute
  '/api/credits/$': typeof ApiCreditsSplatRoute
  '/api/openapi/$': typeof ApiOpenapiSplatRoute
  '/api/polar/webhook': typeof ApiPolarWebhookRoute
  '/api/posthog/$': typeof ApiPosthogSplatRoute
  '/api/proxy/$': typeof ApiProxySplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/app/organizations/$organizationSlug': typeof AppOrganizationsOrganizationSlugRouteWithChildren
  '/app/organizations/create': typeof AppOrganizationsCreateRoute
  '/app/organizations/~': typeof AppOrganizationsChar126Route
  '/app/settings/activity': typeof AppSettingsActivityRoute
  '/app/settings/credits': typeof AppSettingsCreditsRouteWithChildren
  '/app/settings/keys': typeof AppSettingsKeysRoute
  '/app/settings/preference': typeof AppSettingsPreferenceRoute
  '/app/organizations/': typeof AppOrganizationsIndexRoute
  '/app/settings/': typeof AppSettingsIndexRoute
  '/app/organizations/$organizationSlug/projects': typeof AppOrganizationsOrganizationSlugProjectsRouteWithChildren
  '/app/organizations/$organizationSlug/settings': typeof AppOrganizationsOrganizationSlugSettingsRoute
  '/app/settings/credits/success': typeof AppSettingsCreditsSuccessRoute
  '/app/organizations/$organizationSlug/': typeof AppOrganizationsOrganizationSlugIndexRoute
  '/api/projects/$organizationSlug/$projectSlug/openapi': typeof ApiProjectsOrganizationSlugProjectSlugOpenapiRoute
  '/app/organizations/$organizationSlug/projects/create': typeof AppOrganizationsOrganizationSlugProjectsCreateRoute
  '/app/organizations/$organizationSlug/projects/~': typeof AppOrganizationsOrganizationSlugProjectsChar126Route
  '/app/organizations/$organizationSlug/projects/': typeof AppOrganizationsOrganizationSlugProjectsIndexRoute
  '/app/organizations/$organizationSlug/projects/$projectSlug/explorer': typeof AppOrganizationsOrganizationSlugProjectsProjectSlugExplorerRoute
  '/app/organizations/$organizationSlug/projects/$projectSlug/spec': typeof AppOrganizationsOrganizationSlugProjectsProjectSlugSpecRoute
  '/app/organizations/$organizationSlug/projects/$projectSlug/': typeof AppOrganizationsOrganizationSlugProjectsProjectSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$internal/confirm-test': typeof InternalConfirmTestRoute
  '/$internal/email-templates-preview': typeof InternalEmailTemplatesPreviewRoute
  '/$internal/image-upload-test': typeof InternalImageUploadTestRoute
  '/app/catalogue': typeof AppCatalogueRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/invitations': typeof AppInvitationsRoute
  '/auth/change-password': typeof AuthChangePasswordRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sent-email': typeof AuthSentEmailRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth/two-factor-auth': typeof AuthTwoFactorAuthRoute
  '/auth/two-factor-verify': typeof AuthTwoFactorVerifyRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/mcp/$': typeof McpSplatRoute
  '/app': typeof AppIndexRoute
  '/auth': typeof AuthIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cap/$': typeof ApiCapSplatRoute
  '/api/credits/$': typeof ApiCreditsSplatRoute
  '/api/openapi/$': typeof ApiOpenapiSplatRoute
  '/api/polar/webhook': typeof ApiPolarWebhookRoute
  '/api/posthog/$': typeof ApiPosthogSplatRoute
  '/api/proxy/$': typeof ApiProxySplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/app/organizations/create': typeof AppOrganizationsCreateRoute
  '/app/organizations/~': typeof AppOrganizationsChar126Route
  '/app/settings/activity': typeof AppSettingsActivityRoute
  '/app/settings/credits': typeof AppSettingsCreditsRouteWithChildren
  '/app/settings/keys': typeof AppSettingsKeysRoute
  '/app/settings/preference': typeof AppSettingsPreferenceRoute
  '/app/organizations': typeof AppOrganizationsIndexRoute
  '/app/settings': typeof AppSettingsIndexRoute
  '/app/organizations/$organizationSlug/settings': typeof AppOrganizationsOrganizationSlugSettingsRoute
  '/app/settings/credits/success': typeof AppSettingsCreditsSuccessRoute
  '/app/organizations/$organizationSlug': typeof AppOrganizationsOrganizationSlugIndexRoute
  '/api/projects/$organizationSlug/$projectSlug/openapi': typeof ApiProjectsOrganizationSlugProjectSlugOpenapiRoute
  '/app/organizations/$organizationSlug/projects/create': typeof AppOrganizationsOrganizationSlugProjectsCreateRoute
  '/app/organizations/$organizationSlug/projects/~': typeof AppOrganizationsOrganizationSlugProjectsChar126Route
  '/app/organizations/$organizationSlug/projects': typeof AppOrganizationsOrganizationSlugProjectsIndexRoute
  '/app/organizations/$organizationSlug/projects/$projectSlug/explorer': typeof AppOrganizationsOrganizationSlugProjectsProjectSlugExplorerRoute
  '/app/organizations/$organizationSlug/projects/$projectSlug/spec': typeof AppOrganizationsOrganizationSlugProjectsProjectSlugSpecRoute
  '/app/organizations/$organizationSlug/projects/$projectSlug': typeof AppOrganizationsOrganizationSlugProjectsProjectSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/$internal/confirm-test': typeof InternalConfirmTestRoute
  '/$internal/email-templates-preview': typeof InternalEmailTemplatesPreviewRoute
  '/$internal/image-upload-test': typeof InternalImageUploadTestRoute
  '/app/catalogue': typeof AppCatalogueRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/invitations': typeof AppInvitationsRoute
  '/app/organizations': typeof AppOrganizationsRouteWithChildren
  '/auth/change-password': typeof AuthChangePasswordRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sent-email': typeof AuthSentEmailRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth/two-factor-auth': typeof AuthTwoFactorAuthRoute
  '/auth/two-factor-verify': typeof AuthTwoFactorVerifyRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/mcp/$': typeof McpSplatRoute
  '/app/': typeof AppIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cap/$': typeof ApiCapSplatRoute
  '/api/credits/$': typeof ApiCreditsSplatRoute
  '/api/openapi/$': typeof ApiOpenapiSplatRoute
  '/api/polar/webhook': typeof ApiPolarWebhookRoute
  '/api/posthog/$': typeof ApiPosthogSplatRoute
  '/api/proxy/$': typeof ApiProxySplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/app/organizations/$organizationSlug': typeof AppOrganizationsOrganizationSlugRouteWithChildren
  '/app/organizations/create': typeof AppOrganizationsCreateRoute
  '/app/organizations/~': typeof AppOrganizationsChar126Route
  '/app/settings/activity': typeof AppSettingsActivityRoute
  '/app/settings/credits': typeof AppSettingsCreditsRouteWithChildren
  '/app/settings/keys': typeof AppSettingsKeysRoute
  '/app/settings/preference': typeof AppSettingsPreferenceRoute
  '/app/organizations/': typeof AppOrganizationsIndexRoute
  '/app/settings/': typeof AppSettingsIndexRoute
  '/app/organizations/$organizationSlug/projects': typeof AppOrganizationsOrganizationSlugProjectsRouteWithChildren
  '/app/organizations/$organizationSlug/settings': typeof AppOrganizationsOrganizationSlugSettingsRoute
  '/app/settings/credits/success': typeof AppSettingsCreditsSuccessRoute
  '/app/organizations/$organizationSlug/': typeof AppOrganizationsOrganizationSlugIndexRoute
  '/api/projects/$organizationSlug/$projectSlug/openapi': typeof ApiProjectsOrganizationSlugProjectSlugOpenapiRoute
  '/app/organizations/$organizationSlug/projects/create': typeof AppOrganizationsOrganizationSlugProjectsCreateRoute
  '/app/organizations/$organizationSlug/projects/~': typeof AppOrganizationsOrganizationSlugProjectsChar126Route
  '/app/organizations/$organizationSlug/projects/': typeof AppOrganizationsOrganizationSlugProjectsIndexRoute
  '/app/organizations/$organizationSlug/projects/$projectSlug/explorer': typeof AppOrganizationsOrganizationSlugProjectsProjectSlugExplorerRoute
  '/app/organizations/$organizationSlug/projects/$projectSlug/spec': typeof AppOrganizationsOrganizationSlugProjectsProjectSlugSpecRoute
  '/app/organizations/$organizationSlug/projects/$projectSlug/': typeof AppOrganizationsOrganizationSlugProjectsProjectSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/$internal/confirm-test'
    | '/$internal/email-templates-preview'
    | '/$internal/image-upload-test'
    | '/app/catalogue'
    | '/app/dashboard'
    | '/app/invitations'
    | '/app/organizations'
    | '/auth/change-password'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/auth/sent-email'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/auth/two-factor-auth'
    | '/auth/two-factor-verify'
    | '/auth/verify-email'
    | '/mcp/$'
    | '/app/'
    | '/auth/'
    | '/api/auth/$'
    | '/api/cap/$'
    | '/api/credits/$'
    | '/api/openapi/$'
    | '/api/polar/webhook'
    | '/api/posthog/$'
    | '/api/proxy/$'
    | '/api/trpc/$'
    | '/app/organizations/$organizationSlug'
    | '/app/organizations/create'
    | '/app/organizations/~'
    | '/app/settings/activity'
    | '/app/settings/credits'
    | '/app/settings/keys'
    | '/app/settings/preference'
    | '/app/organizations/'
    | '/app/settings/'
    | '/app/organizations/$organizationSlug/projects'
    | '/app/organizations/$organizationSlug/settings'
    | '/app/settings/credits/success'
    | '/app/organizations/$organizationSlug/'
    | '/api/projects/$organizationSlug/$projectSlug/openapi'
    | '/app/organizations/$organizationSlug/projects/create'
    | '/app/organizations/$organizationSlug/projects/~'
    | '/app/organizations/$organizationSlug/projects/'
    | '/app/organizations/$organizationSlug/projects/$projectSlug/explorer'
    | '/app/organizations/$organizationSlug/projects/$projectSlug/spec'
    | '/app/organizations/$organizationSlug/projects/$projectSlug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$internal/confirm-test'
    | '/$internal/email-templates-preview'
    | '/$internal/image-upload-test'
    | '/app/catalogue'
    | '/app/dashboard'
    | '/app/invitations'
    | '/auth/change-password'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/auth/sent-email'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/auth/two-factor-auth'
    | '/auth/two-factor-verify'
    | '/auth/verify-email'
    | '/mcp/$'
    | '/app'
    | '/auth'
    | '/api/auth/$'
    | '/api/cap/$'
    | '/api/credits/$'
    | '/api/openapi/$'
    | '/api/polar/webhook'
    | '/api/posthog/$'
    | '/api/proxy/$'
    | '/api/trpc/$'
    | '/app/organizations/create'
    | '/app/organizations/~'
    | '/app/settings/activity'
    | '/app/settings/credits'
    | '/app/settings/keys'
    | '/app/settings/preference'
    | '/app/organizations'
    | '/app/settings'
    | '/app/organizations/$organizationSlug/settings'
    | '/app/settings/credits/success'
    | '/app/organizations/$organizationSlug'
    | '/api/projects/$organizationSlug/$projectSlug/openapi'
    | '/app/organizations/$organizationSlug/projects/create'
    | '/app/organizations/$organizationSlug/projects/~'
    | '/app/organizations/$organizationSlug/projects'
    | '/app/organizations/$organizationSlug/projects/$projectSlug/explorer'
    | '/app/organizations/$organizationSlug/projects/$projectSlug/spec'
    | '/app/organizations/$organizationSlug/projects/$projectSlug'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/$internal/confirm-test'
    | '/$internal/email-templates-preview'
    | '/$internal/image-upload-test'
    | '/app/catalogue'
    | '/app/dashboard'
    | '/app/invitations'
    | '/app/organizations'
    | '/auth/change-password'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/auth/sent-email'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/auth/two-factor-auth'
    | '/auth/two-factor-verify'
    | '/auth/verify-email'
    | '/mcp/$'
    | '/app/'
    | '/auth/'
    | '/api/auth/$'
    | '/api/cap/$'
    | '/api/credits/$'
    | '/api/openapi/$'
    | '/api/polar/webhook'
    | '/api/posthog/$'
    | '/api/proxy/$'
    | '/api/trpc/$'
    | '/app/organizations/$organizationSlug'
    | '/app/organizations/create'
    | '/app/organizations/~'
    | '/app/settings/activity'
    | '/app/settings/credits'
    | '/app/settings/keys'
    | '/app/settings/preference'
    | '/app/organizations/'
    | '/app/settings/'
    | '/app/organizations/$organizationSlug/projects'
    | '/app/organizations/$organizationSlug/settings'
    | '/app/settings/credits/success'
    | '/app/organizations/$organizationSlug/'
    | '/api/projects/$organizationSlug/$projectSlug/openapi'
    | '/app/organizations/$organizationSlug/projects/create'
    | '/app/organizations/$organizationSlug/projects/~'
    | '/app/organizations/$organizationSlug/projects/'
    | '/app/organizations/$organizationSlug/projects/$projectSlug/explorer'
    | '/app/organizations/$organizationSlug/projects/$projectSlug/spec'
    | '/app/organizations/$organizationSlug/projects/$projectSlug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  InternalConfirmTestRoute: typeof InternalConfirmTestRoute
  InternalEmailTemplatesPreviewRoute: typeof InternalEmailTemplatesPreviewRoute
  InternalImageUploadTestRoute: typeof InternalImageUploadTestRoute
  AuthChangePasswordRoute: typeof AuthChangePasswordRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSentEmailRoute: typeof AuthSentEmailRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  AuthTwoFactorAuthRoute: typeof AuthTwoFactorAuthRoute
  AuthTwoFactorVerifyRoute: typeof AuthTwoFactorVerifyRoute
  AuthVerifyEmailRoute: typeof AuthVerifyEmailRoute
  McpSplatRoute: typeof McpSplatRoute
  AuthIndexRoute: typeof AuthIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiCapSplatRoute: typeof ApiCapSplatRoute
  ApiCreditsSplatRoute: typeof ApiCreditsSplatRoute
  ApiOpenapiSplatRoute: typeof ApiOpenapiSplatRoute
  ApiPolarWebhookRoute: typeof ApiPolarWebhookRoute
  ApiPosthogSplatRoute: typeof ApiPosthogSplatRoute
  ApiProxySplatRoute: typeof ApiProxySplatRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
  ApiProjectsOrganizationSlugProjectSlugOpenapiRoute: typeof ApiProjectsOrganizationSlugProjectSlugOpenapiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/mcp/$': {
      id: '/mcp/$'
      path: '/mcp/$'
      fullPath: '/mcp/$'
      preLoaderRoute: typeof McpSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verify-email': {
      id: '/auth/verify-email'
      path: '/auth/verify-email'
      fullPath: '/auth/verify-email'
      preLoaderRoute: typeof AuthVerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/two-factor-verify': {
      id: '/auth/two-factor-verify'
      path: '/auth/two-factor-verify'
      fullPath: '/auth/two-factor-verify'
      preLoaderRoute: typeof AuthTwoFactorVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/two-factor-auth': {
      id: '/auth/two-factor-auth'
      path: '/auth/two-factor-auth'
      fullPath: '/auth/two-factor-auth'
      preLoaderRoute: typeof AuthTwoFactorAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/auth/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sent-email': {
      id: '/auth/sent-email'
      path: '/auth/sent-email'
      fullPath: '/auth/sent-email'
      preLoaderRoute: typeof AuthSentEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/change-password': {
      id: '/auth/change-password'
      path: '/auth/change-password'
      fullPath: '/auth/change-password'
      preLoaderRoute: typeof AuthChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/organizations': {
      id: '/app/organizations'
      path: '/organizations'
      fullPath: '/app/organizations'
      preLoaderRoute: typeof AppOrganizationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/invitations': {
      id: '/app/invitations'
      path: '/invitations'
      fullPath: '/app/invitations'
      preLoaderRoute: typeof AppInvitationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/catalogue': {
      id: '/app/catalogue'
      path: '/catalogue'
      fullPath: '/app/catalogue'
      preLoaderRoute: typeof AppCatalogueRouteImport
      parentRoute: typeof AppRoute
    }
    '/$internal/image-upload-test': {
      id: '/$internal/image-upload-test'
      path: '/$internal/image-upload-test'
      fullPath: '/$internal/image-upload-test'
      preLoaderRoute: typeof InternalImageUploadTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$internal/email-templates-preview': {
      id: '/$internal/email-templates-preview'
      path: '/$internal/email-templates-preview'
      fullPath: '/$internal/email-templates-preview'
      preLoaderRoute: typeof InternalEmailTemplatesPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$internal/confirm-test': {
      id: '/$internal/confirm-test'
      path: '/$internal/confirm-test'
      fullPath: '/$internal/confirm-test'
      preLoaderRoute: typeof InternalConfirmTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/settings/': {
      id: '/app/settings/'
      path: '/settings'
      fullPath: '/app/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/organizations/': {
      id: '/app/organizations/'
      path: '/'
      fullPath: '/app/organizations/'
      preLoaderRoute: typeof AppOrganizationsIndexRouteImport
      parentRoute: typeof AppOrganizationsRoute
    }
    '/app/settings/preference': {
      id: '/app/settings/preference'
      path: '/settings/preference'
      fullPath: '/app/settings/preference'
      preLoaderRoute: typeof AppSettingsPreferenceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings/keys': {
      id: '/app/settings/keys'
      path: '/settings/keys'
      fullPath: '/app/settings/keys'
      preLoaderRoute: typeof AppSettingsKeysRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings/credits': {
      id: '/app/settings/credits'
      path: '/settings/credits'
      fullPath: '/app/settings/credits'
      preLoaderRoute: typeof AppSettingsCreditsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings/activity': {
      id: '/app/settings/activity'
      path: '/settings/activity'
      fullPath: '/app/settings/activity'
      preLoaderRoute: typeof AppSettingsActivityRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/organizations/~': {
      id: '/app/organizations/~'
      path: '/~'
      fullPath: '/app/organizations/~'
      preLoaderRoute: typeof AppOrganizationsChar126RouteImport
      parentRoute: typeof AppOrganizationsRoute
    }
    '/app/organizations/create': {
      id: '/app/organizations/create'
      path: '/create'
      fullPath: '/app/organizations/create'
      preLoaderRoute: typeof AppOrganizationsCreateRouteImport
      parentRoute: typeof AppOrganizationsRoute
    }
    '/app/organizations/$organizationSlug': {
      id: '/app/organizations/$organizationSlug'
      path: '/$organizationSlug'
      fullPath: '/app/organizations/$organizationSlug'
      preLoaderRoute: typeof AppOrganizationsOrganizationSlugRouteImport
      parentRoute: typeof AppOrganizationsRoute
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/proxy/$': {
      id: '/api/proxy/$'
      path: '/api/proxy/$'
      fullPath: '/api/proxy/$'
      preLoaderRoute: typeof ApiProxySplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/posthog/$': {
      id: '/api/posthog/$'
      path: '/api/posthog/$'
      fullPath: '/api/posthog/$'
      preLoaderRoute: typeof ApiPosthogSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/polar/webhook': {
      id: '/api/polar/webhook'
      path: '/api/polar/webhook'
      fullPath: '/api/polar/webhook'
      preLoaderRoute: typeof ApiPolarWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/openapi/$': {
      id: '/api/openapi/$'
      path: '/api/openapi/$'
      fullPath: '/api/openapi/$'
      preLoaderRoute: typeof ApiOpenapiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/credits/$': {
      id: '/api/credits/$'
      path: '/api/credits/$'
      fullPath: '/api/credits/$'
      preLoaderRoute: typeof ApiCreditsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cap/$': {
      id: '/api/cap/$'
      path: '/api/cap/$'
      fullPath: '/api/cap/$'
      preLoaderRoute: typeof ApiCapSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/organizations/$organizationSlug/': {
      id: '/app/organizations/$organizationSlug/'
      path: '/'
      fullPath: '/app/organizations/$organizationSlug/'
      preLoaderRoute: typeof AppOrganizationsOrganizationSlugIndexRouteImport
      parentRoute: typeof AppOrganizationsOrganizationSlugRoute
    }
    '/app/settings/credits/success': {
      id: '/app/settings/credits/success'
      path: '/success'
      fullPath: '/app/settings/credits/success'
      preLoaderRoute: typeof AppSettingsCreditsSuccessRouteImport
      parentRoute: typeof AppSettingsCreditsRoute
    }
    '/app/organizations/$organizationSlug/settings': {
      id: '/app/organizations/$organizationSlug/settings'
      path: '/settings'
      fullPath: '/app/organizations/$organizationSlug/settings'
      preLoaderRoute: typeof AppOrganizationsOrganizationSlugSettingsRouteImport
      parentRoute: typeof AppOrganizationsOrganizationSlugRoute
    }
    '/app/organizations/$organizationSlug/projects': {
      id: '/app/organizations/$organizationSlug/projects'
      path: '/projects'
      fullPath: '/app/organizations/$organizationSlug/projects'
      preLoaderRoute: typeof AppOrganizationsOrganizationSlugProjectsRouteImport
      parentRoute: typeof AppOrganizationsOrganizationSlugRoute
    }
    '/app/organizations/$organizationSlug/projects/': {
      id: '/app/organizations/$organizationSlug/projects/'
      path: '/'
      fullPath: '/app/organizations/$organizationSlug/projects/'
      preLoaderRoute: typeof AppOrganizationsOrganizationSlugProjectsIndexRouteImport
      parentRoute: typeof AppOrganizationsOrganizationSlugProjectsRoute
    }
    '/app/organizations/$organizationSlug/projects/~': {
      id: '/app/organizations/$organizationSlug/projects/~'
      path: '/~'
      fullPath: '/app/organizations/$organizationSlug/projects/~'
      preLoaderRoute: typeof AppOrganizationsOrganizationSlugProjectsChar126RouteImport
      parentRoute: typeof AppOrganizationsOrganizationSlugProjectsRoute
    }
    '/app/organizations/$organizationSlug/projects/create': {
      id: '/app/organizations/$organizationSlug/projects/create'
      path: '/create'
      fullPath: '/app/organizations/$organizationSlug/projects/create'
      preLoaderRoute: typeof AppOrganizationsOrganizationSlugProjectsCreateRouteImport
      parentRoute: typeof AppOrganizationsOrganizationSlugProjectsRoute
    }
    '/api/projects/$organizationSlug/$projectSlug/openapi': {
      id: '/api/projects/$organizationSlug/$projectSlug/openapi'
      path: '/api/projects/$organizationSlug/$projectSlug/openapi'
      fullPath: '/api/projects/$organizationSlug/$projectSlug/openapi'
      preLoaderRoute: typeof ApiProjectsOrganizationSlugProjectSlugOpenapiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/organizations/$organizationSlug/projects/$projectSlug/': {
      id: '/app/organizations/$organizationSlug/projects/$projectSlug/'
      path: '/$projectSlug'
      fullPath: '/app/organizations/$organizationSlug/projects/$projectSlug/'
      preLoaderRoute: typeof AppOrganizationsOrganizationSlugProjectsProjectSlugIndexRouteImport
      parentRoute: typeof AppOrganizationsOrganizationSlugProjectsRoute
    }
    '/app/organizations/$organizationSlug/projects/$projectSlug/spec': {
      id: '/app/organizations/$organizationSlug/projects/$projectSlug/spec'
      path: '/$projectSlug/spec'
      fullPath: '/app/organizations/$organizationSlug/projects/$projectSlug/spec'
      preLoaderRoute: typeof AppOrganizationsOrganizationSlugProjectsProjectSlugSpecRouteImport
      parentRoute: typeof AppOrganizationsOrganizationSlugProjectsRoute
    }
    '/app/organizations/$organizationSlug/projects/$projectSlug/explorer': {
      id: '/app/organizations/$organizationSlug/projects/$projectSlug/explorer'
      path: '/$projectSlug/explorer'
      fullPath: '/app/organizations/$organizationSlug/projects/$projectSlug/explorer'
      preLoaderRoute: typeof AppOrganizationsOrganizationSlugProjectsProjectSlugExplorerRouteImport
      parentRoute: typeof AppOrganizationsOrganizationSlugProjectsRoute
    }
  }
}

interface AppOrganizationsOrganizationSlugProjectsRouteChildren {
  AppOrganizationsOrganizationSlugProjectsCreateRoute: typeof AppOrganizationsOrganizationSlugProjectsCreateRoute
  AppOrganizationsOrganizationSlugProjectsChar126Route: typeof AppOrganizationsOrganizationSlugProjectsChar126Route
  AppOrganizationsOrganizationSlugProjectsIndexRoute: typeof AppOrganizationsOrganizationSlugProjectsIndexRoute
  AppOrganizationsOrganizationSlugProjectsProjectSlugExplorerRoute: typeof AppOrganizationsOrganizationSlugProjectsProjectSlugExplorerRoute
  AppOrganizationsOrganizationSlugProjectsProjectSlugSpecRoute: typeof AppOrganizationsOrganizationSlugProjectsProjectSlugSpecRoute
  AppOrganizationsOrganizationSlugProjectsProjectSlugIndexRoute: typeof AppOrganizationsOrganizationSlugProjectsProjectSlugIndexRoute
}

const AppOrganizationsOrganizationSlugProjectsRouteChildren: AppOrganizationsOrganizationSlugProjectsRouteChildren =
  {
    AppOrganizationsOrganizationSlugProjectsCreateRoute:
      AppOrganizationsOrganizationSlugProjectsCreateRoute,
    AppOrganizationsOrganizationSlugProjectsChar126Route:
      AppOrganizationsOrganizationSlugProjectsChar126Route,
    AppOrganizationsOrganizationSlugProjectsIndexRoute:
      AppOrganizationsOrganizationSlugProjectsIndexRoute,
    AppOrganizationsOrganizationSlugProjectsProjectSlugExplorerRoute:
      AppOrganizationsOrganizationSlugProjectsProjectSlugExplorerRoute,
    AppOrganizationsOrganizationSlugProjectsProjectSlugSpecRoute:
      AppOrganizationsOrganizationSlugProjectsProjectSlugSpecRoute,
    AppOrganizationsOrganizationSlugProjectsProjectSlugIndexRoute:
      AppOrganizationsOrganizationSlugProjectsProjectSlugIndexRoute,
  }

const AppOrganizationsOrganizationSlugProjectsRouteWithChildren =
  AppOrganizationsOrganizationSlugProjectsRoute._addFileChildren(
    AppOrganizationsOrganizationSlugProjectsRouteChildren,
  )

interface AppOrganizationsOrganizationSlugRouteChildren {
  AppOrganizationsOrganizationSlugProjectsRoute: typeof AppOrganizationsOrganizationSlugProjectsRouteWithChildren
  AppOrganizationsOrganizationSlugSettingsRoute: typeof AppOrganizationsOrganizationSlugSettingsRoute
  AppOrganizationsOrganizationSlugIndexRoute: typeof AppOrganizationsOrganizationSlugIndexRoute
}

const AppOrganizationsOrganizationSlugRouteChildren: AppOrganizationsOrganizationSlugRouteChildren =
  {
    AppOrganizationsOrganizationSlugProjectsRoute:
      AppOrganizationsOrganizationSlugProjectsRouteWithChildren,
    AppOrganizationsOrganizationSlugSettingsRoute:
      AppOrganizationsOrganizationSlugSettingsRoute,
    AppOrganizationsOrganizationSlugIndexRoute:
      AppOrganizationsOrganizationSlugIndexRoute,
  }

const AppOrganizationsOrganizationSlugRouteWithChildren =
  AppOrganizationsOrganizationSlugRoute._addFileChildren(
    AppOrganizationsOrganizationSlugRouteChildren,
  )

interface AppOrganizationsRouteChildren {
  AppOrganizationsOrganizationSlugRoute: typeof AppOrganizationsOrganizationSlugRouteWithChildren
  AppOrganizationsCreateRoute: typeof AppOrganizationsCreateRoute
  AppOrganizationsChar126Route: typeof AppOrganizationsChar126Route
  AppOrganizationsIndexRoute: typeof AppOrganizationsIndexRoute
}

const AppOrganizationsRouteChildren: AppOrganizationsRouteChildren = {
  AppOrganizationsOrganizationSlugRoute:
    AppOrganizationsOrganizationSlugRouteWithChildren,
  AppOrganizationsCreateRoute: AppOrganizationsCreateRoute,
  AppOrganizationsChar126Route: AppOrganizationsChar126Route,
  AppOrganizationsIndexRoute: AppOrganizationsIndexRoute,
}

const AppOrganizationsRouteWithChildren =
  AppOrganizationsRoute._addFileChildren(AppOrganizationsRouteChildren)

interface AppSettingsCreditsRouteChildren {
  AppSettingsCreditsSuccessRoute: typeof AppSettingsCreditsSuccessRoute
}

const AppSettingsCreditsRouteChildren: AppSettingsCreditsRouteChildren = {
  AppSettingsCreditsSuccessRoute: AppSettingsCreditsSuccessRoute,
}

const AppSettingsCreditsRouteWithChildren =
  AppSettingsCreditsRoute._addFileChildren(AppSettingsCreditsRouteChildren)

interface AppRouteChildren {
  AppCatalogueRoute: typeof AppCatalogueRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppInvitationsRoute: typeof AppInvitationsRoute
  AppOrganizationsRoute: typeof AppOrganizationsRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  AppSettingsActivityRoute: typeof AppSettingsActivityRoute
  AppSettingsCreditsRoute: typeof AppSettingsCreditsRouteWithChildren
  AppSettingsKeysRoute: typeof AppSettingsKeysRoute
  AppSettingsPreferenceRoute: typeof AppSettingsPreferenceRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCatalogueRoute: AppCatalogueRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppInvitationsRoute: AppInvitationsRoute,
  AppOrganizationsRoute: AppOrganizationsRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  AppSettingsActivityRoute: AppSettingsActivityRoute,
  AppSettingsCreditsRoute: AppSettingsCreditsRouteWithChildren,
  AppSettingsKeysRoute: AppSettingsKeysRoute,
  AppSettingsPreferenceRoute: AppSettingsPreferenceRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  InternalConfirmTestRoute: InternalConfirmTestRoute,
  InternalEmailTemplatesPreviewRoute: InternalEmailTemplatesPreviewRoute,
  InternalImageUploadTestRoute: InternalImageUploadTestRoute,
  AuthChangePasswordRoute: AuthChangePasswordRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSentEmailRoute: AuthSentEmailRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  AuthTwoFactorAuthRoute: AuthTwoFactorAuthRoute,
  AuthTwoFactorVerifyRoute: AuthTwoFactorVerifyRoute,
  AuthVerifyEmailRoute: AuthVerifyEmailRoute,
  McpSplatRoute: McpSplatRoute,
  AuthIndexRoute: AuthIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiCapSplatRoute: ApiCapSplatRoute,
  ApiCreditsSplatRoute: ApiCreditsSplatRoute,
  ApiOpenapiSplatRoute: ApiOpenapiSplatRoute,
  ApiPolarWebhookRoute: ApiPolarWebhookRoute,
  ApiPosthogSplatRoute: ApiPosthogSplatRoute,
  ApiProxySplatRoute: ApiProxySplatRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
  ApiProjectsOrganizationSlugProjectSlugOpenapiRoute:
    ApiProjectsOrganizationSlugProjectSlugOpenapiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
