name: Format and Fix

on:
  workflow_dispatch:

env:
  MISE_EXPERIMENTAL: true

jobs:
  format-fix:
    runs-on: ubuntu-slim
    timeout-minutes: 10
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/cache@v5
        with:
          path: ~/.local/share/pnpm/store
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      - uses: jdx/mise-action@v2
      - name: Install dependencies
        run: pnpm install
      - name: Run format script
        run: pnpm run format
      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git diff --staged --quiet || git commit -m "chore: apply eslint --fix and prettier --write"
          git push
